(() => {
'use strict';
const {createFrameLoop,SharedField2D,createWorldDirector,clamp,lerp}=window.AetherRuntime;
const $=s=>document.querySelector(s);
const canvas=$('#world'), mapCanvas=$('#minimap'), mapCtx=mapCanvas.getContext('2d');
const ui={location:$('#locationLabel'),field:$('#fieldValue'),wind:$('#windValue'),charge:$('#chargeValue'),fps:$('#fpsValue'),bearing:$('#bearing'),mission:$('#mission'),missionTitle:$('#missionTitle'),missionBody:$('#missionBody'),missionProgress:$('#missionProgress'),inspection:$('#inspection'),scanId:$('#scanId'),scanName:$('#scanName'),scanDesc:$('#scanDesc'),scanBiome:$('#scanBiome'),scanCore:$('#scanCore'),scanFlux:$('#scanFlux'),scanAge:$('#scanAge'),flightBtn:$('#flightBtn'),scanBtn:$('#scanBtn'),stormBtn:$('#stormBtn'),solarBtn:$('#solarBtn'),soundBtn:$('#soundBtn'),closeInspection:$('#closeInspection'),eventBanner:$('#eventBanner'),eventKicker:$('#eventKicker'),eventName:$('#eventName'),eventPhase:$('#eventPhase'),toast:$('#toast'),unsupported:$('#unsupported'),stick:$('#mobileStick'),look:$('#mobileLook')};
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const gl=canvas.getContext('webgl2',{antialias:false,alpha:false,depth:true,premultipliedAlpha:false,powerPreference:'high-performance'});
if(!gl){ui.unsupported.hidden=false;return;}
const debugRendererExt=gl.getExtension('WEBGL_debug_renderer_info');
const gpuRenderer=debugRendererExt?gl.getParameter(debugRendererExt.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);
const softwareRenderer=/swiftshader|software/i.test(String(gpuRenderer));

const PI=Math.PI,TAU=PI*2;
const v3=(x=0,y=0,z=0)=>new Float32Array([x,y,z]);
const vcopy=a=>v3(a[0],a[1],a[2]);
const vadd=(a,b,out=v3())=>(out[0]=a[0]+b[0],out[1]=a[1]+b[1],out[2]=a[2]+b[2],out);
const vsub=(a,b,out=v3())=>(out[0]=a[0]-b[0],out[1]=a[1]-b[1],out[2]=a[2]-b[2],out);
const vscale=(a,s,out=v3())=>(out[0]=a[0]*s,out[1]=a[1]*s,out[2]=a[2]*s,out);
const vdot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const vcross=(a,b,out=v3())=>(out[0]=a[1]*b[2]-a[2]*b[1],out[1]=a[2]*b[0]-a[0]*b[2],out[2]=a[0]*b[1]-a[1]*b[0],out);
const vlen=a=>Math.hypot(a[0],a[1],a[2]);
const vnorm=(a,out=v3())=>{const l=vlen(a)||1;return vscale(a,1/l,out)};
const vlerp=(a,b,t,out=v3())=>(out[0]=lerp(a[0],b[0],t),out[1]=lerp(a[1],b[1],t),out[2]=lerp(a[2],b[2],t),out);
const smooth=t=>t*t*(3-2*t);
const smoother=t=>t*t*t*(t*(t*6-15)+10);

function m4(){return new Float32Array(16)}
function mIdentity(){const o=m4();o[0]=o[5]=o[10]=o[15]=1;return o}
function mMul(a,b,out=m4()){for(let c=0;c<4;c++)for(let r=0;r<4;r++)out[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return out}
function mPerspective(fovy,aspect,near,far,out=m4()){const f=1/Math.tan(fovy/2),nf=1/(near-far);out.fill(0);out[0]=f/aspect;out[5]=f;out[10]=(far+near)*nf;out[11]=-1;out[14]=2*far*near*nf;return out}
function mLookAt(eye,target,up=v3(0,1,0),out=m4()){const z=vnorm(vsub(eye,target)),x=vnorm(vcross(up,z)),y=vcross(z,x);out.set([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-vdot(x,eye),-vdot(y,eye),-vdot(z,eye),1]);return out}
function mCompose(pos,scale=[1,1,1],yaw=0,pitch=0,roll=0,out=m4()){const cy=Math.cos(yaw),sy=Math.sin(yaw),cx=Math.cos(pitch),sx=Math.sin(pitch),cz=Math.cos(roll),sz=Math.sin(roll);const r00=cy*cz+sy*sx*sz,r01=-cy*sz+sy*sx*cz,r02=sy*cx;const r10=cx*sz,r11=cx*cz,r12=-sx;const r20=-sy*cz+cy*sx*sz,r21=sy*sz+cy*sx*cz,r22=cy*cx;out.set([r00*scale[0],r10*scale[0],r20*scale[0],0,r01*scale[1],r11*scale[1],r21*scale[1],0,r02*scale[2],r12*scale[2],r22*scale[2],0,pos[0],pos[1],pos[2],1]);return out}
function mBasisBetween(a,b,width,height,out=m4()){const dir=vsub(b,a),len=vlen(dir)||1;vscale(dir,1/len,dir);let right=vcross(v3(0,1,0),dir);if(vlen(right)<.001)right=v3(1,0,0);vnorm(right,right);const up=vcross(dir,right);const mid=vscale(vadd(a,b),.5);out.set([right[0]*width,right[1]*width,right[2]*width,0,up[0]*height,up[1]*height,up[2]*height,0,dir[0]*len,dir[1]*len,dir[2]*len,0,mid[0],mid[1],mid[2],1]);return out}
function transformPoint(m,p,out=v3()){const x=p[0],y=p[1],z=p[2],w=m[3]*x+m[7]*y+m[11]*z+m[15]||1;out[0]=(m[0]*x+m[4]*y+m[8]*z+m[12])/w;out[1]=(m[1]*x+m[5]*y+m[9]*z+m[13])/w;out[2]=(m[2]*x+m[6]*y+m[10]*z+m[14])/w;return out}

function mulberry32(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function hash2(x,y,seed=0){const s=Math.sin(x*127.1+y*311.7+seed*74.7)*43758.5453123;return s-Math.floor(s)}
function noise2(x,y,seed=0){const ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,u=fx*fx*(3-2*fx),v=fy*fy*(3-2*fy);const a=hash2(ix,iy,seed),b=hash2(ix+1,iy,seed),c=hash2(ix,iy+1,seed),d=hash2(ix+1,iy+1,seed);return lerp(lerp(a,b,u),lerp(c,d,u),v)}
function fbm(x,y,seed=0){let s=0,a=.5,f=1;for(let i=0;i<4;i++){s+=a*noise2(x*f,y*f,seed+i*17);f*=2.03;a*=.48}return s}

function compile(type,source,label){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const message=gl.getShaderInfoLog(s);console.error(label,message);throw new Error(`${label}: ${message}`)}return s}
function program(vs,fs,label){const p=gl.createProgram();gl.attachShader(p,compile(gl.VERTEX_SHADER,vs,`${label} vertex`));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,fs,`${label} fragment`));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(`${label}: ${gl.getProgramInfoLog(p)}`);return p}
function uniforms(p,names){const o={};for(const n of names)o[n]=gl.getUniformLocation(p,n);return o}

const SHARED_GLSL=`
float sat(float x){return clamp(x,0.0,1.0);}float hash21(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}float noise21(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash21(i),hash21(i+vec2(1,0)),f.x),mix(hash21(i+vec2(0,1)),hash21(i+1.0),f.x),f.y);}float fbm21(vec2 p){float a=.5,s=0.;for(int i=0;i<4;i++){s+=a*noise21(p);p=p*2.03+13.1;a*=.48;}return s;}`;

const skyProgram=program(`#version 300 es
precision highp float;const vec2 P[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));out vec2 vUv;void main(){vUv=P[gl_VertexID]*.5+.5;gl_Position=vec4(P[gl_VertexID],0,1);}`,`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform float uTime,uTempest,uSolar,uAspect;uniform vec2 uLook;${SHARED_GLSL}
void main(){vec2 uv=vUv;vec2 p=(uv-.5)*vec2(uAspect,1.);float horizon=smoothstep(-.12,.72,uv.y);vec3 zen=mix(vec3(.012,.026,.075),vec3(.025,.065,.105),1.-uTempest);vec3 low=mix(vec3(.14,.38,.46),vec3(.035,.10,.15),uTempest);vec3 col=mix(low,zen,horizon);float sunSize=mix(.018,.026,uSolar);vec2 sunPos=vec2(.66-.14*uLook.x,.66+.05*uLook.y);float sun=pow(sat(1.-length((uv-sunPos)*vec2(uAspect,1.))/sunSize),5.);col+=sun*mix(vec3(1.1,.72,.38),vec3(1.6,.92,.44),uSolar)*2.4;float halo=pow(sat(1.-length((uv-sunPos)*vec2(uAspect,1.))/.22),3.);col+=halo*vec3(.35,.24,.14)*(1.+uSolar*1.5);float aur=fbm21(vec2(uv.x*2.2+uTime*.012,uv.y*5.));aur*=smoothstep(.42,.75,uv.y)*smoothstep(1.,.54,uv.y);col+=vec3(.05,.30,.31)*pow(aur,3.)*(.55+uSolar*.7);float storm=fbm21(vec2(uv.x*5.+uTime*.02,uv.y*3.-uTime*.01));col+=uTempest*vec3(.12,.025,.18)*pow(storm,2.);float stars=step(.99915,hash21(floor(uv*vec2(520.,300.))));stars*=smoothstep(.45,.9,uv.y)*(1.-uTempest*.8);col+=stars*vec3(.7,.9,1.2);float cloud=fbm21(vec2(uv.x*3.2+uTime*.006,uv.y*5.));cloud=smoothstep(.54,.82,cloud)*smoothstep(.5,-.08,uv.y);col=mix(col,col+vec3(.2,.27,.29)*cloud,.8);outColor=vec4(col,1);}`, 'sky');
const skyU=uniforms(skyProgram,['uTime','uTempest','uSolar','uAspect','uLook']);

const meshProgram=program(`#version 300 es
precision highp float;layout(location=0)in vec3 aPos;layout(location=1)in vec3 aNormal;layout(location=2)in vec3 aColor;layout(location=3)in float aMaterial;uniform mat4 uViewProj,uModel;out vec3 vWorld,vNormal,vColor,vLocal;flat out int vMaterial;void main(){vec4 world=uModel*vec4(aPos,1);vWorld=world.xyz;vNormal=normalize(mat3(uModel)*aNormal);vColor=aColor;vLocal=aPos;vMaterial=int(aMaterial+.5);gl_Position=uViewProj*world;}`,`#version 300 es
precision highp float;in vec3 vWorld,vNormal,vColor,vLocal;flat in int vMaterial;out vec4 outColor;uniform vec3 uEye,uSunDir,uSunColor;uniform float uTime,uTempest,uSolar,uInspect,uOpacity;${SHARED_GLSL}
void main(){vec3 n=normalize(vNormal),v=normalize(uEye-vWorld),l=normalize(uSunDir);float ndl=max(dot(n,l),0.);float rim=pow(1.-max(dot(n,v),0.),3.);float rough=.85,metal=0.,emit=0.;vec3 base=vColor;if(vMaterial==0){rough=.94;float strata=.8+.2*sin(vLocal.y*.42+fbm21(vWorld.xz*.025)*7.);base*=strata;base+=vec3(.018,.025,.026)*noise21(vWorld.xz*.12);}else if(vMaterial==1){rough=.34;float moss=noise21(vWorld.xz*.09+vWorld.y*.02);base*=.75+.35*moss;emit=.09+.16*moss+uSolar*.08;}else if(vMaterial==2){rough=.08;metal=.12;emit=.48+uTempest*.7+uSolar*.65;base=mix(base,vec3(.08,.78,1.2),uTempest*.55);base=mix(base,vec3(1.2,.62,.18),uSolar*.5);}else if(vMaterial==3){rough=.24;metal=.78;base*=.7+.3*sin(vLocal.y*.7);emit=uInspect*.18;}vec3 ambient=base*mix(vec3(.24,.31,.33),vec3(.13,.18,.25),uTempest);vec3 diffuse=base*ndl*uSunColor*(1.-metal*.3);vec3 h=normalize(l+v);float spec=pow(max(dot(n,h),0.),mix(9.,90.,1.-rough));vec3 specular=mix(vec3(.12),base,metal)*spec*(.25+1.1*(1.-rough));float contact=smoothstep(-180.,30.,vWorld.y);vec3 col=(ambient+diffuse+specular)*mix(.62,1.,contact);col+=rim*mix(vec3(.05,.14,.17),vec3(.16,.68,.86),1.-rough);col+=base*emit*(.6+.4*sin(uTime*2.+vWorld.y*.08));float d=length(uEye-vWorld);float fog=smoothstep(620.,1900.,d);vec3 fogCol=mix(vec3(.055,.13,.17),vec3(.035,.045,.09),uTempest);col=mix(col,fogCol,fog*.86);outColor=vec4(col,uOpacity);}`, 'mesh');
const meshU=uniforms(meshProgram,['uViewProj','uModel','uEye','uSunDir','uSunColor','uTime','uTempest','uSolar','uInspect','uOpacity']);

const instancedProgram=program(`#version 300 es
precision highp float;precision highp int;layout(location=0)in vec3 aPos;layout(location=1)in vec3 aNormal;layout(location=2)in vec3 aColor;layout(location=4)in vec4 iM0;layout(location=5)in vec4 iM1;layout(location=6)in vec4 iM2;layout(location=7)in vec4 iM3;layout(location=8)in vec4 iColor;layout(location=9)in vec4 iExtra;uniform mat4 uViewProj;uniform float uTime;uniform int uKind;out vec3 vWorld,vNormal,vColor,vLocal;out vec4 vExtra;void main(){mat4 model=mat4(iM0,iM1,iM2,iM3);vec3 p=aPos;if(uKind==0){float bend=(sin(uTime*1.8+iExtra.x)*.35+iExtra.y*.9)*p.y;p.x+=bend*.22;p.z+=(cos(uTime*1.4+iExtra.x)*.28+iExtra.z*.9)*p.y*.22;}else if(uKind==2){p.y+=sin(uTime*4.+iExtra.x)*abs(p.x)*.16;p.z+=sin(uTime*2.+iExtra.x)*.04;}vec4 world=model*vec4(p,1);vWorld=world.xyz;vNormal=normalize(mat3(model)*aNormal);vColor=aColor*iColor.rgb;vLocal=p;vExtra=iExtra;gl_Position=uViewProj*world;}`,`#version 300 es
precision highp float;precision highp int;in vec3 vWorld,vNormal,vColor,vLocal;in vec4 vExtra;out vec4 outColor;uniform vec3 uEye,uSunDir,uSunColor;uniform float uTime,uTempest,uSolar,uOpacity;uniform int uMaterial,uKind;${SHARED_GLSL}
void main(){vec3 n=normalize(vNormal),v=normalize(uEye-vWorld),l=normalize(uSunDir),h=normalize(v+l);float nd=max(dot(n,l),0.),rim=pow(1.-max(dot(n,v),0.),3.);vec3 base=vColor;float rough=.62,metal=0.,emit=0.;if(uMaterial==1){rough=.38;emit=.07+vExtra.w*.11;}if(uMaterial==2){rough=.06;emit=.55+vExtra.w*.5+uTempest*.7+uSolar*.65;}if(uMaterial==3){rough=.22;metal=.68;emit=uSolar*.12;}float spec=pow(max(dot(n,h),0.),mix(12.,110.,1.-rough));vec3 col=base*(.22+.78*nd)*uSunColor+mix(vec3(.12),base,metal)*spec*(.2+1.1*(1.-rough));col+=rim*base*(.25+.5*(1.-rough));col+=base*emit*(.75+.25*sin(uTime*2.4+vExtra.x));if(uKind==2)col+=vec3(.05,.22,.27)*pow(rim,1.4);float fog=smoothstep(700.,1900.,length(uEye-vWorld));col=mix(col,mix(vec3(.055,.13,.17),vec3(.03,.04,.085),uTempest),fog*.85);outColor=vec4(col,uOpacity);}`, 'instanced');
const instU=uniforms(instancedProgram,['uViewProj','uTime','uKind','uEye','uSunDir','uSunColor','uTempest','uSolar','uOpacity','uMaterial']);

const particleProgram=program(`#version 300 es
precision highp float;layout(location=0)in vec3 aPos;layout(location=1)in float aSize;layout(location=2)in float aSeed;layout(location=3)in float aType;uniform mat4 uViewProj;uniform float uTime,uPixelRatio,uTempest,uSolar;out float vSeed,vType,vFade;void main(){vec3 p=aPos;if(aType<.5)p.y+=sin(uTime*.12+aSeed*8.)*10.;else if(aType<1.5)p.y+=sin(uTime*.7+aSeed*11.)*3.;vec4 clip=uViewProj*vec4(p,1);gl_Position=clip;gl_PointSize=clamp(aSize*uPixelRatio*(700./max(1.,clip.w)),1.,210.);vFade=smoothstep(1900.,180.,clip.w);vSeed=aSeed;vType=aType;}`,`#version 300 es
precision highp float;in float vSeed,vType,vFade;out vec4 outColor;uniform float uTime,uTempest,uSolar;${SHARED_GLSL}
void main(){vec2 p=gl_PointCoord-.5;float r=length(p);float a;if(vType<.5){float n=noise21(gl_PointCoord*4.+vSeed*8.);a=smoothstep(.52,.12,r)*(.34+.3*n);vec3 c=mix(vec3(.19,.34,.37),vec3(.16,.21,.32),uTempest);outColor=vec4(c,a*vFade*.22);}else if(vType<1.5){a=smoothstep(.5,.05,r);vec3 c=mix(vec3(.18,.8,.86),vec3(1.,.64,.24),uSolar);outColor=vec4(c,a*vFade*.28);}else{float ring=smoothstep(.48,.24,r)*smoothstep(.02,.25,r);vec3 c=mix(vec3(.25,.7,1.2),vec3(.9,.22,.75),uTempest);outColor=vec4(c,ring*vFade*.62);}if(outColor.a<.01)discard;}`, 'particles');
const particleU=uniforms(particleProgram,['uViewProj','uTime','uPixelRatio','uTempest','uSolar']);

const lineProgram=program(`#version 300 es
precision highp float;layout(location=0)in vec3 aPos;layout(location=1)in vec3 aColor;uniform mat4 uViewProj;out vec3 vColor;void main(){vColor=aColor;gl_Position=uViewProj*vec4(aPos,1);}`,`#version 300 es
precision highp float;in vec3 vColor;out vec4 outColor;uniform float uAlpha;void main(){outColor=vec4(vColor,uAlpha);}`, 'lines');
const lineU=uniforms(lineProgram,['uViewProj','uAlpha']);

const postProgram=program(`#version 300 es
precision highp float;const vec2 P[3]=vec2[3](vec2(-1,-1),vec2(3,-1),vec2(-1,3));out vec2 vUv;void main(){vUv=P[gl_VertexID]*.5+.5;gl_Position=vec4(P[gl_VertexID],0,1);}`,`#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform sampler2D uScene;uniform vec2 uTexel;uniform float uTime,uTempest,uSolar;${SHARED_GLSL}
vec3 sampleScene(vec2 uv){return texture(uScene,uv).rgb;}void main(){vec2 p=vUv-.5;float ca=.00042*(.3+length(p))*(1.+uTempest*.5);vec3 c=vec3(sampleScene(vUv+vec2(ca,0)).r,sampleScene(vUv).g,sampleScene(vUv-vec2(ca,0)).b);vec3 b=sampleScene(vUv+uTexel*vec2(2,0))+sampleScene(vUv-uTexel*vec2(2,0))+sampleScene(vUv+uTexel*vec2(0,2))+sampleScene(vUv-uTexel*vec2(0,2));b=max(b*.25-.54,0.);c+=b*(.28+uTempest*.28+uSolar*.18);float vig=smoothstep(.92,.22,length(p*vec2(1.05,1.)));c*=mix(.58,1.,vig);float grain=hash21(gl_FragCoord.xy+uTime*60.)-.5;c+=grain*.018;c=1.-exp(-c*1.12);c=pow(c,vec3(.94));outColor=vec4(c,1);}`, 'post');
const postU=uniforms(postProgram,['uScene','uTexel','uTime','uTempest','uSolar']);

function computeNormals(pos,idx){const n=new Float32Array(pos.length);for(let i=0;i<idx.length;i+=3){const ia=idx[i]*3,ib=idx[i+1]*3,ic=idx[i+2]*3,ax=pos[ia],ay=pos[ia+1],az=pos[ia+2],bx=pos[ib],by=pos[ib+1],bz=pos[ib+2],cx=pos[ic],cy=pos[ic+1],cz=pos[ic+2],abx=bx-ax,aby=by-ay,abz=bz-az,acx=cx-ax,acy=cy-ay,acz=cz-az,nx=aby*acz-abz*acy,ny=abz*acx-abx*acz,nz=abx*acy-aby*acx;n[ia]+=nx;n[ia+1]+=ny;n[ia+2]+=nz;n[ib]+=nx;n[ib+1]+=ny;n[ib+2]+=nz;n[ic]+=nx;n[ic+1]+=ny;n[ic+2]+=nz}for(let i=0;i<n.length;i+=3){const l=Math.hypot(n[i],n[i+1],n[i+2])||1;n[i]/=l;n[i+1]/=l;n[i+2]/=l}return n}
function createMesh({positions,normals,colors,materials,indices},usage=gl.STATIC_DRAW){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const buffers=[];const bind=(loc,data,size,type=gl.FLOAT)=>{const b=gl.createBuffer();buffers.push(b);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,usage);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,type,false,0,0)};bind(0,positions,3);bind(1,normals||computeNormals(positions,indices),3);bind(2,colors||new Float32Array(positions.length).fill(1),3);bind(3,materials||new Float32Array(positions.length/3),1);const ib=gl.createBuffer();buffers.push(ib);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,indices,usage);gl.bindVertexArray(null);return{vao,buffers,count:indices.length,indexType:indices instanceof Uint32Array?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,mode:gl.TRIANGLES}}
function createLineMesh(maxVertices=1024){const vao=gl.createVertexArray(),pos=new Float32Array(maxVertices*3),col=new Float32Array(maxVertices*3);gl.bindVertexArray(vao);const pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,pos.byteLength,gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);const cb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,cb);gl.bufferData(gl.ARRAY_BUFFER,col.byteLength,gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,0,0);gl.bindVertexArray(null);return{vao,pb,cb,pos,col,count:0,maxVertices}}
function updateLineMesh(mesh,positions,colors){mesh.count=Math.min(positions.length/3,mesh.maxVertices);mesh.pos.set(positions.subarray?positions.subarray(0,mesh.count*3):positions.slice(0,mesh.count*3));mesh.col.set(colors.subarray?colors.subarray(0,mesh.count*3):colors.slice(0,mesh.count*3));gl.bindBuffer(gl.ARRAY_BUFFER,mesh.pb);gl.bufferSubData(gl.ARRAY_BUFFER,0,mesh.pos,0,mesh.count*3);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.cb);gl.bufferSubData(gl.ARRAY_BUFFER,0,mesh.col,0,mesh.count*3)}

function islandGeometry(seed=1){const seg=72,rings=18,pos=[],col=[],mat=[],idx=[];const palettes=[[[.055,.075,.083],[.055,.34,.22]],[[.055,.07,.08],[.08,.42,.2]],[[.045,.075,.10],[.08,.30,.44]],[[.07,.055,.06],[.30,.18,.16]],[[.055,.055,.08],[.28,.22,.42]],[[.045,.07,.075],[.10,.38,.34]],[[.075,.06,.045],[.40,.28,.12]]],pal=palettes[Math.max(0,Math.min(palettes.length-1,Math.round(seed/11)-1))],rock=pal[0],mossColor=pal[1];const heightAt=(r,a)=>{const x=Math.cos(a)*r*2.4,z=Math.sin(a)*r*2.4;const macro=(fbm(x,z,seed)-.5)*.28;const ridges=Math.sin(a*(4+(seed%4))+seed)*.05*(.2+r);return(1-r*r)*.23+macro*(1-r*.45)+ridges};for(let r=0;r<=rings;r++){const u=r/rings;for(let i=0;i<seg;i++){const a=i/seg*TAU;const edge=1+(.055*Math.sin(a*(5+seed%3)+seed)+.035*Math.sin(a*11+seed*.7))*u*u;const rr=u*edge;const h=heightAt(u,a);pos.push(Math.cos(a)*rr,h,Math.sin(a)*rr);const moss=clamp((h+.02)*2.8*(1-u*.55),0,1);col.push(lerp(rock[0],mossColor[0],moss),lerp(rock[1],mossColor[1],moss),lerp(rock[2],mossColor[2],moss));mat.push(moss>.34?1:0)}}for(let r=0;r<rings;r++)for(let i=0;i<seg;i++){const j=(i+1)%seg,a=r*seg+i,b=r*seg+j,c=(r+1)*seg+i,d=(r+1)*seg+j;idx.push(a,c,b,b,c,d)}const sideStart=pos.length/3,underRings=11;for(let r=0;r<=underRings;r++){const u=r/underRings;for(let i=0;i<seg;i++){const a=i/seg*TAU,edge=1+(.055*Math.sin(a*(5+seed%3)+seed)+.035*Math.sin(a*11+seed*.7));const rad=lerp(edge,.025,smoother(u))+.035*Math.sin(u*PI),topY=heightAt(1,a),y=lerp(topY,-1.18,u)-.11*Math.sin(u*PI)+Math.sin(a*7+seed)*.018*(1-u);pos.push(Math.cos(a)*rad,y,Math.sin(a)*rad);const stripe=.65+.35*Math.sin(u*24+a*3+seed);col.push(.04*stripe,.055*stripe,.06*stripe);mat.push(r>.52&&((i+seed)%13<2)?3:0)}}for(let r=0;r<underRings;r++)for(let i=0;i<seg;i++){const j=(i+1)%seg,a=sideStart+r*seg+i,b=sideStart+r*seg+j,c=sideStart+(r+1)*seg+i,d=sideStart+(r+1)*seg+j;idx.push(a,b,c,b,d,c)}return{mesh:createMesh({positions:new Float32Array(pos),colors:new Float32Array(col),materials:new Float32Array(mat),indices:new Uint32Array(idx)}),heightAt}}
function boxGeometry(color=[.4,.5,.55],material=3){const p=[-.5,-.5,-.5,.5,-.5,-.5,.5,.5,-.5,-.5,.5,-.5,-.5,-.5,.5,.5,-.5,.5,.5,.5,.5,-.5,.5,.5],idx=[0,1,2,0,2,3,4,6,5,4,7,6,0,4,5,0,5,1,3,2,6,3,6,7,1,5,6,1,6,2,0,3,7,0,7,4],c=[],m=[];for(let i=0;i<8;i++){c.push(...color);m.push(material)}return createMesh({positions:new Float32Array(p),colors:new Float32Array(c),materials:new Float32Array(m),indices:new Uint16Array(idx)})}
function cylinderGeometry(segments=18,color=[.22,.32,.34],material=3){const p=[],c=[],m=[],idx=[];for(let y=0;y<=1;y++)for(let i=0;i<segments;i++){const a=i/segments*TAU;p.push(Math.cos(a)*.5,y-.5,Math.sin(a)*.5);c.push(...color);m.push(material)}for(let i=0;i<segments;i++){const j=(i+1)%segments,a=i,b=j,d=segments+i,e=segments+j;idx.push(a,d,b,b,d,e)}const bottom=p.length/3;p.push(0,-.5,0);c.push(...color);m.push(material);const top=p.length/3;p.push(0,.5,0);c.push(...color);m.push(material);for(let i=0;i<segments;i++){const j=(i+1)%segments;idx.push(bottom,j,i,top,segments+i,segments+j)}return createMesh({positions:new Float32Array(p),colors:new Float32Array(c),materials:new Float32Array(m),indices:new Uint16Array(idx)})}
function crystalGeometry(){const p=[0,1.2,0,-.45,0,0,0,0,.38,.45,0,0,0,0,-.38,0,-.45,0,0,-.82,0],idx=[0,1,2,0,2,3,0,3,4,0,4,1,5,2,1,5,3,2,5,4,3,5,1,4],c=[];for(let i=0;i<7;i++)c.push(.16,.78,1);return{positions:new Float32Array(p),normals:computeNormals(new Float32Array(p),new Uint16Array(idx)),colors:new Float32Array(c),indices:new Uint16Array(idx)}}
function reedGeometry(){const p=[-.05,0,0,.05,0,0,.025,1,0,-.025,1,0,0,0,-.05,0,0,.05,0,1,.025,0,1,-.025],idx=[0,1,2,0,2,3,4,5,6,4,6,7],c=[];for(let i=0;i<8;i++)c.push(.13,.55,.38);return{positions:new Float32Array(p),normals:computeNormals(new Float32Array(p),new Uint16Array(idx)),colors:new Float32Array(c),indices:new Uint16Array(idx)}}
function gliderGeometry(){const p=[0,.04,.78,-1,0,-.12,-.34,.05,.22,0,.12,-.08,.34,.05,.22,1,0,-.12,0,-.03,-.65],idx=[0,1,2,0,2,3,0,3,4,0,4,5,1,6,2,2,6,3,3,6,4,4,6,5],c=[];for(let i=0;i<7;i++)c.push(i===3?.28:.08,i===3?.85:.42,i===3?.9:.48);return{positions:new Float32Array(p),normals:computeNormals(new Float32Array(p),new Uint16Array(idx)),colors:new Float32Array(c),indices:new Uint16Array(idx)}}
function ringGeometry(segments=48){const p=[],c=[],m=[],idx=[];for(let i=0;i<segments;i++){const a=i/segments*TAU,b=(i+1)/segments*TAU;const i0=p.length/3;for(const [r,y] of [[.94,-.04],[1.06,-.04],[1.06,.04],[.94,.04]]){p.push(Math.cos(a)*r,y,Math.sin(a)*r);c.push(.12,.75,1);m.push(2)}const j0=p.length/3;for(const [r,y] of [[.94,-.04],[1.06,-.04],[1.06,.04],[.94,.04]]){p.push(Math.cos(b)*r,y,Math.sin(b)*r);c.push(.12,.75,1);m.push(2)}idx.push(i0,i0+1,j0,i0+1,j0+1,j0,i0+2,i0+3,j0+2,i0+3,j0+3,j0+2,i0,i0+2,j0,i0+2,j0+2,j0,i0+1,j0+1,i0+3,i0+3,j0+1,j0+3)}return createMesh({positions:new Float32Array(p),colors:new Float32Array(c),materials:new Float32Array(m),indices:new Uint32Array(idx)})}

function createInstancedBatch(base,instances,dynamic=false){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const buffers=[];const bindBase=(loc,data,size)=>{const b=gl.createBuffer();buffers.push(b);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,0,0)};bindBase(0,base.positions,3);bindBase(1,base.normals,3);bindBase(2,base.colors,3);const ib=gl.createBuffer();buffers.push(ib);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,base.indices,gl.STATIC_DRAW);const stride=24*4,data=new Float32Array(instances.length*24),instBuf=gl.createBuffer();buffers.push(instBuf);gl.bindBuffer(gl.ARRAY_BUFFER,instBuf);gl.bufferData(gl.ARRAY_BUFFER,data.byteLength,dynamic?gl.DYNAMIC_DRAW:gl.STATIC_DRAW);for(let i=0;i<4;i++){gl.enableVertexAttribArray(4+i);gl.vertexAttribPointer(4+i,4,gl.FLOAT,false,stride,i*16);gl.vertexAttribDivisor(4+i,1)}gl.enableVertexAttribArray(8);gl.vertexAttribPointer(8,4,gl.FLOAT,false,stride,64);gl.vertexAttribDivisor(8,1);gl.enableVertexAttribArray(9);gl.vertexAttribPointer(9,4,gl.FLOAT,false,stride,80);gl.vertexAttribDivisor(9,1);gl.bindVertexArray(null);const batch={vao,buffers,instBuf,data,count:instances.length,indexCount:base.indices.length,indexType:base.indices instanceof Uint32Array?gl.UNSIGNED_INT:gl.UNSIGNED_SHORT,instances,dynamic};updateInstances(batch);return batch}
function updateInstances(batch){let o=0;for(const it of batch.instances){batch.data.set(it.model,o);o+=16;batch.data.set(it.color||[1,1,1,1],o);o+=4;batch.data.set(it.extra||[0,0,0,0],o);o+=4}gl.bindBuffer(gl.ARRAY_BUFFER,batch.instBuf);gl.bufferSubData(gl.ARRAY_BUFFER,0,batch.data)}

const islandSpecs=[
{id:'AE-01',name:'Meridian Crown',biome:'Luminous heath',desc:'The primary regulator island. Its buried flywheel keeps the northern sky-current coherent.',age:'2.7k cycles',pos:v3(0,92,0),radius:165,height:82,seed:11,accent:[.12,.86,1]},
{id:'AE-02',name:'Verdant Relay',biome:'Rain orchard',desc:'A humid nursery where reed forests condense drinkable mist around copper vanes.',age:'1.9k cycles',pos:v3(-410,34,-210),radius:128,height:72,seed:22,accent:[.18,1,.54]},
{id:'AE-03',name:'Glasswake',biome:'Crystal barrens',desc:'A fractured lens-field that amplifies solar charge and bends distant silhouettes.',age:'3.4k cycles',pos:v3(420,122,-330),radius:116,height:66,seed:33,accent:[.45,.7,1]},
{id:'AE-04',name:'Sable Loom',biome:'Basalt terraces',desc:'Dense black shelves woven with alloy conduits and old lightning scars.',age:'4.1k cycles',pos:v3(540,-12,190),radius:144,height:86,seed:44,accent:[1,.42,.5]},
{id:'AE-05',name:'Iris Hollow',biome:'Spore wetlands',desc:'A bowl-shaped refuge where charged spores travel in stable vortices.',age:'1.2k cycles',pos:v3(-510,148,310),radius:112,height:62,seed:55,accent:[.72,.4,1]},
{id:'AE-06',name:'North Lantern',biome:'Aurora steppe',desc:'The highest inhabited station, tuned to the polar aurora and long-range migration.',age:'2.2k cycles',pos:v3(80,310,-690),radius:94,height:58,seed:66,accent:[.4,1,.88]},
{id:'AE-07',name:'Ember Reach',biome:'Solar scrub',desc:'A warm frontier island whose mirrored fins store the last light of each cycle.',age:'980 cycles',pos:v3(-180,-48,650),radius:122,height:78,seed:77,accent:[1,.68,.22]}
];
const islands=islandSpecs.map(spec=>{const geo=islandGeometry(spec.seed),model=mCompose(spec.pos,[spec.radius,spec.height,spec.radius],(spec.seed%9)*.13);return{...spec,...geo,model,corePhase:(spec.seed*.71)%TAU}});
const cylinder=cylinderGeometry(),box=boxGeometry(),solarBox=boxGeometry([1,.44,.12],2),ring=ringGeometry();

const structures=[];
for(const island of islands){const base=vadd(island.pos,v3(0,island.height*.26,0));const towerScale=island.id==='AE-01'?[12,island.height*.72,12]:[7,island.height*.42,7];structures.push({mesh:cylinder,model:mCompose(base,towerScale,island.seed*.2),island,kind:'tower'});if(island.id==='AE-01'){for(let i=0;i<3;i++){const a=i/3*TAU+.4,p=vadd(island.pos,v3(Math.cos(a)*48,island.height*.23,Math.sin(a)*48));structures.push({mesh:cylinder,model:mCompose(p,[5,42,5],a),island,kind:'spire'})}}}

const vegetationInstances=[],crystalInstances=[];
for(const island of islands){const rnd=mulberry32(island.seed*9029),count=island.id==='AE-01'?44:22;for(let i=0;i<count;i++){const a=rnd()*TAU,r=Math.sqrt(rnd())*.76,h=island.heightAt(r,a),wp=vadd(island.pos,v3(Math.cos(a)*r*island.radius,h*island.height+2,Math.sin(a)*r*island.radius));const s=lerp(4.5,12,rnd())*(island.biome.includes('barrens')?.55:1);vegetationInstances.push({model:mCompose(wp,[s*.7,s,s*.7],rnd()*TAU),color:[lerp(.55,.95,rnd()),lerp(.75,1,rnd()),lerp(.62,.94,rnd()),1],extra:[rnd()*TAU,0,0,0],island})}const crystals=island.id==='AE-03'?26:island.id==='AE-01'?18:7;for(let i=0;i<crystals;i++){const a=rnd()*TAU,r=lerp(.18,.82,Math.sqrt(rnd())),h=island.heightAt(r,a),wp=vadd(island.pos,v3(Math.cos(a)*r*island.radius,h*island.height+3,Math.sin(a)*r*island.radius));const s=lerp(5,17,rnd())*(island.id==='AE-03'?1.25:1);crystalInstances.push({model:mCompose(wp,[s*.42,s,s*.42],rnd()*TAU,lerp(-.18,.18,rnd())),color:[...island.accent,1],extra:[rnd()*TAU,0,0,.3],island})}}
const vegetationBatch=createInstancedBatch(reedGeometry(),vegetationInstances,true);
const crystalBatch=createInstancedBatch(crystalGeometry(),crystalInstances,true);

const gliderInstances=[],gliders=[];const gliderRnd=mulberry32(91827);
for(let i=0;i<24;i++){const p=v3((gliderRnd()-.5)*1100,lerp(80,340,gliderRnd()),(gliderRnd()-.5)*1100),g={pos:p,vel:v3((gliderRnd()-.5)*18,(gliderRnd()-.5)*4,(gliderRnd()-.5)*18),phase:gliderRnd()*TAU,speed:lerp(17,34,gliderRnd())};gliders.push(g);const inst={model:mCompose(p,[8,8,8],0),color:[lerp(.55,1,gliderRnd()),lerp(.72,1,gliderRnd()),1,1],extra:[g.phase,0,0,.4],glider:g};gliderInstances.push(inst)}
const gliderBatch=createInstancedBatch(gliderGeometry(),gliderInstances,true);

function createParticleBatch(count,type,seed,bounds){const rnd=mulberry32(seed),positions=new Float32Array(count*3),sizes=new Float32Array(count),seeds=new Float32Array(count),types=new Float32Array(count);for(let i=0;i<count;i++){const p=bounds(rnd,i);positions[i*3]=p[0];positions[i*3+1]=p[1];positions[i*3+2]=p[2];sizes[i]=p[3];seeds[i]=rnd();types[i]=type}const vao=gl.createVertexArray();gl.bindVertexArray(vao);const pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,positions,gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);const sb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,sb);gl.bufferData(gl.ARRAY_BUFFER,sizes,gl.STATIC_DRAW);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,1,gl.FLOAT,false,0,0);const rb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,rb);gl.bufferData(gl.ARRAY_BUFFER,seeds,gl.STATIC_DRAW);gl.enableVertexAttribArray(2);gl.vertexAttribPointer(2,1,gl.FLOAT,false,0,0);const tb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,tb);gl.bufferData(gl.ARRAY_BUFFER,types,gl.STATIC_DRAW);gl.enableVertexAttribArray(3);gl.vertexAttribPointer(3,1,gl.FLOAT,false,0,0);gl.bindVertexArray(null);return{vao,pb,positions,sizes,seeds,types,count,type}}
const cloudBatch=createParticleBatch(360,0,801,(rnd)=>[(rnd()-.5)*2900,lerp(-170,35,Math.pow(rnd(),2.2)),(rnd()-.5)*2900,lerp(90,270,rnd())]);
const moteBatch=createParticleBatch(140,1,802,(rnd)=>[(rnd()-.5)*1800,lerp(-10,520,rnd()),(rnd()-.5)*1800,lerp(1.8,5.5,rnd())]);
const stormBatch=createParticleBatch(150,2,803,(rnd,i)=>{const a=rnd()*TAU,r=lerp(18,210,Math.pow(rnd(),.62)),y=lerp(-70,420,rnd());return[Math.cos(a)*r,y,Math.sin(a)*r,lerp(5,15,rnd())]});
const scanLines=createLineMesh(1800),lightningLines=createLineMesh(900);

const state={time:0,tempest:0,solar:.08,solarMemory:.08,inspect:0,selected:null,stormAnchor:null,autopilot:true,manual:false,quality:1,renderScale:softwareRenderer?.58:1,frame:0,fieldTick:0,telemetryTick:0,mapTick:0,toastTimer:0,bannerTimer:0,fps:60,avgDelta:1/60,contextLost:false};
const field=new SharedField2D({width:64,height:64,channels:4,bounds:[-1450,-1450,1450,1450]});
const fieldSample=new Float32Array(4);
function rebuildField(t){const tempest=state.tempest,solar=state.solar;field.fill((x,z,out)=>{let vx=7.5,vz=-2.2,charge=.17,humidity=.36;for(let i=0;i<islands.length;i++){const p=islands[i].pos,dx=x-p[0],dz=z-p[2],d2=dx*dx+dz*dz+14000,spin=(i%2?.7:-.85)*16000/d2;vx+=-dz*spin;vz+=dx*spin;charge+=Math.exp(-d2/85000)*(.24+(i===0?.2:0));humidity+=Math.exp(-d2/130000)*(i===1||i===4?.34:.08)}const r=Math.hypot(x,z)+1,stormPull=tempest*28*Math.exp(-r/950);vx+=(-x/r)*stormPull+(-z/r)*tempest*9;vz+=(-z/r)*stormPull+(x/r)*tempest*9;const solarPush=solar*9*Math.exp(-r/1200);vx+=(x/r)*solarPush;vz+=(z/r)*solarPush;vx+=Math.sin(z*.006+t*.09)*2.2;vz+=Math.cos(x*.005-t*.07)*2.;charge=clamp(charge+tempest*.46+solar*.28+.08*Math.sin(t*.3+x*.004),0,1.5);humidity=clamp(humidity+tempest*.35-solar*.12,0,1.3);out[0]=vx;out[1]=vz;out[2]=charge;out[3]=humidity;return out})}
rebuildField(0);

const camera={pos:v3(0,190,720),target:v3(0,110,0),yaw:0,pitch:-.08,velocity:v3(),speed:120,shake:v3(),orbitAngle:0};
const cameraForward=v3(),cameraRight=v3(),cameraUp=v3(0,1,0),view=m4(),proj=m4(),viewProj=m4();
const route=[v3(0,205,530),v3(-390,210,330),v3(-560,190,-150),v3(-240,255,-520),v3(220,330,-650),v3(570,180,-250),v3(520,115,310),v3(70,215,540)];
function catmull(a,b,c,d,t,out=v3()){const t2=t*t,t3=t2*t;for(let i=0;i<3;i++)out[i]=.5*((2*b[i])+(-a[i]+c[i])*t+(2*a[i]-5*b[i]+4*c[i]-d[i])*t2+(-a[i]+3*b[i]-3*c[i]+d[i])*t3);return out}
function routePoint(t,out=v3()){const n=route.length,ft=((t%n)+n)%n,i=Math.floor(ft),u=ft-i;return catmull(route[(i-1+n)%n],route[i%n],route[(i+1)%n],route[(i+2)%n],u,out)}
function updateCameraBasis(){const cp=Math.cos(camera.pitch);cameraForward[0]=Math.sin(camera.yaw)*cp;cameraForward[1]=Math.sin(camera.pitch);cameraForward[2]=-Math.cos(camera.yaw)*cp;vnorm(vcross(cameraForward,v3(0,1,0),cameraRight),cameraRight);vnorm(vcross(cameraRight,cameraForward,cameraUp),cameraUp)}
updateCameraBasis();

let targetColor=null,targetDepth=null,targetFbo=null,targetWidth=0,targetHeight=0;
function destroyTargets(){if(targetColor)gl.deleteTexture(targetColor);if(targetDepth)gl.deleteRenderbuffer(targetDepth);if(targetFbo)gl.deleteFramebuffer(targetFbo);targetColor=targetDepth=targetFbo=null}
function ensureTargets(w,h){if(w===targetWidth&&h===targetHeight&&targetFbo)return;destroyTargets();targetWidth=w;targetHeight=h;targetColor=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,targetColor);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,null);targetDepth=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,targetDepth);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT24,w,h);targetFbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,targetFbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,targetColor,0);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,targetDepth);const status=gl.checkFramebufferStatus(gl.FRAMEBUFFER);if(status!==gl.FRAMEBUFFER_COMPLETE)console.warn('Framebuffer incomplete',status);gl.bindFramebuffer(gl.FRAMEBUFFER,null)}
function resize(){const mobile=innerWidth<760,dpr=Math.min(devicePixelRatio||1,mobile?1.15:1.6),scale=state.renderScale,w=Math.max(2,Math.floor(innerWidth*dpr*scale)),h=Math.max(2,Math.floor(innerHeight*dpr*scale));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;ensureTargets(w,h)}mPerspective(mobile?1.08:.88,w/h,.5,4000,proj)}
addEventListener('resize',resize,{passive:true});resize();

function showToast(message,duration=2200){ui.toast.textContent=message;ui.toast.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),duration)}
function showBanner(name,phase,kicker='WORLD EVENT'){ui.eventKicker.textContent=kicker;ui.eventName.textContent=name;ui.eventPhase.textContent=phase;ui.eventBanner.classList.add('show');clearTimeout(state.bannerTimer);state.bannerTimer=setTimeout(()=>ui.eventBanner.classList.remove('show'),reducedMotion?5200:3900)}
function eventEnvelope(t,anticipation=.18,recovery=.25){if(t<anticipation)return smooth(t/anticipation)*.42;if(t>1-recovery)return lerp(1,0,smooth((t-(1-recovery))/recovery));return lerp(.42,1,smooth((t-anticipation)/(1-anticipation-recovery)))}
const director=createWorldDirector({seed:73,minGap:26,maxGap:44,events:[
{name:'tempest',weight:1,duration:16,anticipation:.2,recovery:.3,start(){state.stormAnchor=nearestIsland().island;showBanner('TEMPEST BLOOM','ATMOSPHERIC COLLAPSE DETECTED')},update(e){state.tempest=eventEnvelope(e.t,.2,.3)},end(){state.tempest=0}},
{name:'solar',weight:.82,duration:18,anticipation:.25,recovery:.28,start(){showBanner('SOLAR BRIDGES','ANCIENT ROUTES ARE UNFOLDING')},update(e){state.solar=Math.max(state.solarMemory,eventEnvelope(e.t,.25,.28))},end(){state.solarMemory=Math.min(.32,state.solarMemory+.08);state.solar=state.solarMemory}}
]});
director.on(({type,payload})=>{if(type==='end')showToast(`${payload.event.name==='tempest'?'Tempest dissipated':'Solar route stabilized'}`)});

const keys=new Set();
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyF')toggleFlight();if(e.code==='KeyI')toggleInspection();if(e.code==='Digit1')triggerTempest();if(e.code==='Digit2')triggerSolar();if(e.code==='KeyM')toggleAudio();if(e.code==='Escape'&&state.selected)closeInspection()});
addEventListener('keyup',e=>keys.delete(e.code));
let dragging=false,lastPointer=[0,0],pointerMoved=false;
canvas.addEventListener('pointerdown',e=>{dragging=true;pointerMoved=false;lastPointer=[e.clientX,e.clientY];canvas.setPointerCapture?.(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(!dragging||state.autopilot||state.selected)return;const dx=e.clientX-lastPointer[0],dy=e.clientY-lastPointer[1];if(Math.abs(dx)+Math.abs(dy)>2)pointerMoved=true;camera.yaw-=dx*.003;camera.pitch=clamp(camera.pitch-dy*.0025,-1.25,1.18);lastPointer=[e.clientX,e.clientY];updateCameraBasis()});
canvas.addEventListener('pointerup',e=>{dragging=false;if(!pointerMoved)pickIsland(e.clientX,e.clientY)});
canvas.addEventListener('wheel',e=>{camera.speed=clamp(camera.speed-e.deltaY*.12,45,340);showToast(`Cruise speed ${Math.round(camera.speed)} u/s`,900)},{passive:true});

function toggleFlight(){if(state.selected)closeInspection();state.autopilot=!state.autopilot;state.manual=!state.autopilot;ui.flightBtn.classList.toggle('active',state.manual);ui.flightBtn.querySelector('span').textContent=state.manual?'AUTOPILOT':'TAKE CONTROL';showToast(state.manual?'Manual flight engaged · WASD / QE / drag':'Autopilot route engaged')}
function triggerTempest(){director.trigger('tempest');ui.stormBtn.classList.add('active');setTimeout(()=>ui.stormBtn.classList.remove('active'),1200)}
function triggerSolar(){director.trigger('solar');ui.solarBtn.classList.add('active');setTimeout(()=>ui.solarBtn.classList.remove('active'),1200)}
ui.flightBtn.addEventListener('click',toggleFlight);ui.stormBtn.addEventListener('click',triggerTempest);ui.solarBtn.addEventListener('click',triggerSolar);ui.scanBtn.addEventListener('click',toggleInspection);ui.closeInspection.addEventListener('click',closeInspection);

function toggleInspection(){if(state.selected){closeInspection();return}let nearest=islands[0],best=Infinity;for(const island of islands){const d=vlen(vsub(island.pos,camera.pos));if(d<best){best=d;nearest=island}}openInspection(nearest)}
function openInspection(island){state.selected=island;state.autopilot=false;state.manual=false;camera.orbitAngle=Math.atan2(camera.pos[0]-island.pos[0],camera.pos[2]-island.pos[2]);ui.inspection.classList.add('open');ui.scanBtn.classList.add('active');ui.mission.style.opacity='.2';ui.scanId.textContent=island.id;ui.scanName.textContent=island.name;ui.scanDesc.textContent=island.desc;ui.scanBiome.textContent=island.biome;ui.scanAge.textContent=island.age;showToast(`Deep scan locked: ${island.name}`)}
function closeInspection(){state.selected=null;ui.inspection.classList.remove('open');ui.scanBtn.classList.remove('active');ui.mission.style.opacity='';state.autopilot=true;state.manual=false;showToast('Returning to expedition route')}
function projectToScreen(world){const clip=transformPoint(viewProj,world);return{x:(clip[0]*.5+.5)*innerWidth,y:(-.5*clip[1]+.5)*innerHeight,z:clip[2]}}
function pickIsland(x,y){let best=null,bestD=52;for(const island of islands){const p=projectToScreen(vadd(island.pos,v3(0,island.height*.15,0)));if(p.z<-1||p.z>1)continue;const d=Math.hypot(x-p.x,y-p.y);if(d<bestD){bestD=d;best=island}}if(best)openInspection(best);else if(state.manual)showToast('Drag to look · WASD to fly',1200)}

const touch={moveX:0,moveY:0,lookId:null,stickId:null};
function bindTouch(){let origin=[0,0];ui.stick.addEventListener('pointerdown',e=>{touch.stickId=e.pointerId;origin=[e.clientX,e.clientY];ui.stick.setPointerCapture(e.pointerId);if(state.autopilot)toggleFlight()});ui.stick.addEventListener('pointermove',e=>{if(e.pointerId!==touch.stickId)return;touch.moveX=clamp((e.clientX-origin[0])/38,-1,1);touch.moveY=clamp((e.clientY-origin[1])/38,-1,1);ui.stick.style.setProperty('--x',`${touch.moveX*28}px`);ui.stick.style.setProperty('--y',`${touch.moveY*28}px`)});const end=e=>{if(e.pointerId!==touch.stickId)return;touch.stickId=null;touch.moveX=touch.moveY=0;ui.stick.style.setProperty('--x','0px');ui.stick.style.setProperty('--y','0px')};ui.stick.addEventListener('pointerup',end);ui.stick.addEventListener('pointercancel',end);let lookLast=[0,0];ui.look.addEventListener('pointerdown',e=>{touch.lookId=e.pointerId;lookLast=[e.clientX,e.clientY];ui.look.setPointerCapture(e.pointerId);if(state.autopilot)toggleFlight()});ui.look.addEventListener('pointermove',e=>{if(e.pointerId!==touch.lookId||state.selected)return;camera.yaw-=(e.clientX-lookLast[0])*.004;camera.pitch=clamp(camera.pitch-(e.clientY-lookLast[1])*.003,-1.2,1.12);lookLast=[e.clientX,e.clientY];updateCameraBasis()});ui.look.addEventListener('pointerup',e=>{if(e.pointerId===touch.lookId)touch.lookId=null})}
bindTouch();

let audio=null;
async function toggleAudio(){if(!audio){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx){showToast('Web Audio is unavailable');return}const ctx=new Ctx(),gain=ctx.createGain(),filter=ctx.createBiquadFilter(),hum=ctx.createOscillator(),humGain=ctx.createGain();const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),data=buffer.getChannelData(0),rnd=mulberry32(7721);for(let i=0;i<data.length;i++)data[i]=(rnd()*2-1)*.34;const noise=ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;filter.type='lowpass';filter.frequency.value=520;filter.Q.value=.8;hum.type='sine';hum.frequency.value=46;humGain.gain.value=.04;gain.gain.value=0;noise.connect(filter).connect(gain);hum.connect(humGain).connect(gain);gain.connect(ctx.destination);noise.start();hum.start();audio={ctx,gain,filter,hum,humGain,noise,on:false}}if(audio.ctx.state==='suspended')await audio.ctx.resume();audio.on=!audio.on;audio.gain.gain.setTargetAtTime(audio.on?.23:0,audio.ctx.currentTime,.12);ui.soundBtn.classList.toggle('active',audio.on);ui.soundBtn.setAttribute('aria-pressed',String(audio.on));ui.soundBtn.querySelector('span').textContent=audio.on?'SOUND ON':'SOUND OFF';showToast(audio.on?'Aether soundscape enabled':'Soundscape muted')}
ui.soundBtn.addEventListener('click',toggleAudio);

const coreRaw=crystalGeometry(),coreMesh=createMesh({positions:coreRaw.positions,normals:coreRaw.normals,colors:coreRaw.colors,materials:new Float32Array(coreRaw.positions.length/3).fill(2),indices:coreRaw.indices});
const linePos=new Float32Array(scanLines.maxVertices*3),lineCol=new Float32Array(scanLines.maxVertices*3),lightPos=new Float32Array(lightningLines.maxVertices*3),lightCol=new Float32Array(lightningLines.maxVertices*3);
function updateScanLines(){let n=0;if(state.selected&&state.inspect>.02){const s=state.selected,base=s.pos;for(let ringIndex=0;ringIndex<3;ringIndex++){const radius=s.radius*(.42+ringIndex*.19),y=base[1]-s.height*(.08+ringIndex*.12);for(let i=0;i<48;i++){const a=i/48*TAU,b=(i+1)/48*TAU;for(const q of [a,b]){linePos[n*3]=base[0]+Math.cos(q)*radius;linePos[n*3+1]=y+Math.sin(q*3+s.seed)*2;linePos[n*3+2]=base[2]+Math.sin(q)*radius;lineCol[n*3]=.14;lineCol[n*3+1]=.82;lineCol[n*3+2]=1;n++}}}for(let gz=-1;gz<=1;gz++)for(let gx=-1;gx<=1;gx++){const x=base[0]+gx*s.radius*.24,z=base[2]+gz*s.radius*.24;field.sample(x,z,fieldSample);const start=v3(x,base[1]+s.height*.3,z),end=vadd(start,v3(fieldSample[0]*1.8,fieldSample[2]*9,fieldSample[1]*1.8));for(const p of [start,end]){linePos[n*3]=p[0];linePos[n*3+1]=p[1];linePos[n*3+2]=p[2];lineCol[n*3]=.2;lineCol[n*3+1]=.62+.2*fieldSample[2];lineCol[n*3+2]=1;n++}}const coreTop=vadd(base,v3(0,-s.height*.35,0));for(let spoke=0;spoke<6;spoke++){const a=spoke/6*TAU+state.time*.12;const end=vadd(coreTop,v3(Math.cos(a)*s.radius*.52,Math.sin(a*3)*s.height*.08,Math.sin(a)*s.radius*.52));for(const p of [coreTop,end]){linePos[n*3]=p[0];linePos[n*3+1]=p[1];linePos[n*3+2]=p[2];lineCol[n*3]=.78;lineCol[n*3+1]=.38;lineCol[n*3+2]=1;n++}}}updateLineMesh(scanLines,linePos.subarray(0,n*3),lineCol.subarray(0,n*3))}
function updateLightningLines(){let n=0;if(state.tempest>.025){const c=(state.stormAnchor||islands[0]).pos;for(let bolt=0;bolt<11;bolt++){const a=bolt/11*TAU+Math.sin(state.time*.7+bolt)*.18,rad=lerp(30,190,(bolt%5)/4),start=vadd(c,v3(Math.cos(a)*rad,lerp(70,260,(bolt%4)/3),Math.sin(a)*rad)),end=vadd(c,v3(Math.cos(a+.25)*rad*.35,lerp(-70,35,(bolt%3)/2),Math.sin(a+.25)*rad*.35));let last=start;for(let j=1;j<=7;j++){const t=j/7,p=vlerp(start,end,t),wobble=(1-Math.abs(t-.5)*2)*18;p[0]+=Math.sin(state.time*9+bolt*3+j*2.7)*wobble;p[2]+=Math.cos(state.time*8+bolt*2+j*3.1)*wobble;for(const q of [last,p]){lightPos[n*3]=q[0];lightPos[n*3+1]=q[1];lightPos[n*3+2]=q[2];lightCol[n*3]=.45;lightCol[n*3+1]=.72;lightCol[n*3+2]=1;n++}last=p}}}updateLineMesh(lightningLines,lightPos.subarray(0,n*3),lightCol.subarray(0,n*3))}

function updateParticles(dt){for(const batch of [cloudBatch,moteBatch]){const stride=batch.type===0?4:2;for(let i=state.frame%stride;i<batch.count;i+=stride){const k=i*3,x=batch.positions[k],z=batch.positions[k+2];field.sample(x,z,fieldSample);const speed=batch.type===0?.18:.48;batch.positions[k]+=fieldSample[0]*dt*speed*stride;batch.positions[k+2]+=fieldSample[1]*dt*speed*stride;if(batch.positions[k]>1500)batch.positions[k]-=3000;if(batch.positions[k]<-1500)batch.positions[k]+=3000;if(batch.positions[k+2]>1500)batch.positions[k+2]-=3000;if(batch.positions[k+2]<-1500)batch.positions[k+2]+=3000}gl.bindBuffer(gl.ARRAY_BUFFER,batch.pb);gl.bufferSubData(gl.ARRAY_BUFFER,0,batch.positions)}if(state.tempest>.01){const c=(state.stormAnchor||islands[0]).pos;for(let i=0;i<stormBatch.count;i++){const k=i*3,seed=stormBatch.seeds[i],y=lerp(-90,470,seed),tight=lerp(230,28,smooth((y+90)/560)),a=state.time*(.55+seed*.65)+seed*TAU*7,r=tight*(.35+.65*hash2(i,8,12));stormBatch.positions[k]=c[0]+Math.cos(a)*r;stormBatch.positions[k+1]=c[1]+y;stormBatch.positions[k+2]=c[2]+Math.sin(a)*r}gl.bindBuffer(gl.ARRAY_BUFFER,stormBatch.pb);gl.bufferSubData(gl.ARRAY_BUFFER,0,stormBatch.positions)}}

function updateFieldConsumers(){for(const it of vegetationInstances){const p=[it.model[12],it.model[14]];field.sample(p[0],p[1],fieldSample);it.extra[1]=fieldSample[0]*.035;it.extra[2]=fieldSample[1]*.035;it.extra[3]=fieldSample[2]}updateInstances(vegetationBatch);for(const it of crystalInstances){field.sample(it.model[12],it.model[14],fieldSample);it.extra[3]=fieldSample[2]}updateInstances(crystalBatch)}
function updateGliders(dt){for(let i=0;i<gliders.length;i++){const g=gliders[i],it=gliderInstances[i];field.sample(g.pos[0],g.pos[2],fieldSample);const desired=v3(fieldSample[0],Math.sin(state.time*.4+g.phase)*2.2+fieldSample[2]*2.5,fieldSample[1]);vnorm(desired,desired);vscale(desired,g.speed,desired);g.vel[0]=lerp(g.vel[0],desired[0],dt*.72);g.vel[1]=lerp(g.vel[1],desired[1],dt*.6);g.vel[2]=lerp(g.vel[2],desired[2],dt*.72);for(const island of islands){const d=vsub(g.pos,island.pos),dist=vlen(d);if(dist<island.radius*1.35){vnorm(d,d);g.vel[0]+=d[0]*dt*48;g.vel[1]+=Math.abs(d[1])*dt*12+dt*8;g.vel[2]+=d[2]*dt*48}}g.pos[0]+=g.vel[0]*dt;g.pos[1]+=g.vel[1]*dt;g.pos[2]+=g.vel[2]*dt;if(Math.abs(g.pos[0])>1400)g.pos[0]*=-.92;if(Math.abs(g.pos[2])>1400)g.pos[2]*=-.92;g.pos[1]=clamp(g.pos[1],20,580);const yaw=Math.atan2(g.vel[0],g.vel[2]),pitch=-Math.atan2(g.vel[1],Math.hypot(g.vel[0],g.vel[2]));it.model=mCompose(g.pos,[9,9,9],yaw,pitch,Math.sin(state.time+g.phase)*.12);it.extra[3]=fieldSample[2]}updateInstances(gliderBatch)}

function updateCamera(dt,t){const mobile=innerWidth<760;if(state.selected){state.inspect=lerp(state.inspect,1,1-Math.exp(-dt*2.6));const s=state.selected,r=s.radius*(mobile?2.75:2.3),speed=reducedMotion?.045:.105;camera.orbitAngle+=dt*speed;const desired=vadd(s.pos,v3(Math.sin(camera.orbitAngle)*r,(mobile?s.height*.28:-s.height*.08)+22,Math.cos(camera.orbitAngle)*r));camera.pos[0]=lerp(camera.pos[0],desired[0],1-Math.exp(-dt*1.8));camera.pos[1]=lerp(camera.pos[1],desired[1],1-Math.exp(-dt*1.8));camera.pos[2]=lerp(camera.pos[2],desired[2],1-Math.exp(-dt*1.8));vlerp(s.pos,vadd(s.pos,v3(0,-s.height*.42,0)),state.inspect*.88,camera.target);const d=vsub(camera.target,camera.pos);camera.yaw=Math.atan2(d[0],-d[2]);camera.pitch=Math.atan2(d[1],Math.hypot(d[0],d[2]));updateCameraBasis()}else if(state.autopilot){state.inspect=lerp(state.inspect,0,1-Math.exp(-dt*2));const rate=reducedMotion?.025:.052,p=routePoint(t*rate),ahead=routePoint(t*rate+.38);if(!reducedMotion){p[1]+=Math.sin(t*.22)*12;p[0]+=Math.sin(t*.09)*7}camera.pos[0]=lerp(camera.pos[0],p[0],1-Math.exp(-dt*.9));camera.pos[1]=lerp(camera.pos[1],p[1],1-Math.exp(-dt*.9));camera.pos[2]=lerp(camera.pos[2],p[2],1-Math.exp(-dt*.9));const focus=vlerp(ahead,islands[0].pos,.18,camera.target),d=vsub(focus,camera.pos);camera.yaw=Math.atan2(d[0],-d[2]);camera.pitch=Math.atan2(d[1],Math.hypot(d[0],d[2]));updateCameraBasis()}else{state.inspect=lerp(state.inspect,0,1-Math.exp(-dt*2));updateCameraBasis();let f=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-touch.moveY,s=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+touch.moveX,u=(keys.has('KeyE')?1:0)-(keys.has('KeyQ')?1:0),boost=(keys.has('ShiftLeft')||keys.has('ShiftRight'))?2.1:1;const desired=v3();vadd(desired,vscale(cameraForward,f*camera.speed*boost),desired);vadd(desired,vscale(cameraRight,s*camera.speed*.8*boost),desired);desired[1]+=u*camera.speed*.72;const k=1-Math.exp(-dt*3.2);camera.velocity[0]=lerp(camera.velocity[0],desired[0],k);camera.velocity[1]=lerp(camera.velocity[1],desired[1],k);camera.velocity[2]=lerp(camera.velocity[2],desired[2],k);camera.pos[0]+=camera.velocity[0]*dt;camera.pos[1]+=camera.velocity[1]*dt;camera.pos[2]+=camera.velocity[2]*dt;camera.pos[0]=clamp(camera.pos[0],-1500,1500);camera.pos[1]=clamp(camera.pos[1],-90,850);camera.pos[2]=clamp(camera.pos[2],-1500,1500);vadd(camera.pos,cameraForward,camera.target)}const shakeAmp=reducedMotion?0:state.tempest*3.6;camera.shake[0]=Math.sin(t*17.3)*shakeAmp;camera.shake[1]=Math.sin(t*19.7+2)*shakeAmp*.45;camera.shake[2]=Math.cos(t*15.9)*shakeAmp;const eye=vadd(camera.pos,camera.shake),target=state.selected?camera.target:vadd(eye,cameraForward);mLookAt(eye,target,v3(0,1,0),view);mMul(proj,view,viewProj)}

function updateAudio(){if(!audio?.on)return;const now=audio.ctx.currentTime;field.sample(camera.pos[0],camera.pos[2],fieldSample);audio.filter.frequency.setTargetAtTime(lerp(380,1150,clamp(fieldSample[3],0,1))*(1+state.tempest*.35),now,.2);audio.hum.frequency.setTargetAtTime(42+fieldSample[2]*18+state.solar*16,now,.2);audio.humGain.gain.setTargetAtTime(.025+state.solar*.035+state.tempest*.02,now,.3)}

function update(dt,t){state.time=t;state.frame++;director.update(dt,{camera,islands});if(!director.active){state.tempest=lerp(state.tempest,0,1-Math.exp(-dt*1.3));state.solar=lerp(state.solar,state.solarMemory,1-Math.exp(-dt*.7))}state.fieldTick+=dt;if(state.fieldTick>=.1){state.fieldTick-=.1;rebuildField(t);updateFieldConsumers();updateScanLines()}updateCamera(dt,t);updateGliders(dt);updateParticles(dt);updateLightningLines();updateAudio();state.telemetryTick+=dt;if(state.telemetryTick>.2){state.telemetryTick=0;updateHud()}state.mapTick+=dt;if(state.mapTick>.25){state.mapTick=0;drawMap()}}

let drawCalls=0;
function setMeshCommon(){gl.useProgram(meshProgram);gl.uniformMatrix4fv(meshU.uViewProj,false,viewProj);gl.uniform3fv(meshU.uEye,camera.pos);const sunDir=vnorm(v3(lerp(-.48,.34,state.solar),lerp(.72,.88,state.solar),lerp(.28,-.18,state.solar)));gl.uniform3fv(meshU.uSunDir,sunDir);gl.uniform3fv(meshU.uSunColor,new Float32Array([1.05+state.solar*.28,.92+state.solar*.08,.78-state.tempest*.18]));gl.uniform1f(meshU.uTime,state.time);gl.uniform1f(meshU.uTempest,state.tempest);gl.uniform1f(meshU.uSolar,state.solar);gl.uniform1f(meshU.uInspect,state.inspect)}
function drawMeshObject(mesh,model,opacity=1){gl.uniformMatrix4fv(meshU.uModel,false,model);gl.uniform1f(meshU.uOpacity,opacity);gl.bindVertexArray(mesh.vao);gl.drawElements(mesh.mode,mesh.count,mesh.indexType,0);drawCalls++}
function setInstCommon(kind,material,opacity=1){gl.useProgram(instancedProgram);gl.uniformMatrix4fv(instU.uViewProj,false,viewProj);gl.uniform3fv(instU.uEye,camera.pos);const sunDir=vnorm(v3(lerp(-.48,.34,state.solar),lerp(.72,.88,state.solar),lerp(.28,-.18,state.solar)));gl.uniform3fv(instU.uSunDir,sunDir);gl.uniform3fv(instU.uSunColor,new Float32Array([1.05+state.solar*.28,.92+state.solar*.08,.78-state.tempest*.18]));gl.uniform1f(instU.uTime,state.time);gl.uniform1f(instU.uTempest,state.tempest);gl.uniform1f(instU.uSolar,state.solar);gl.uniform1f(instU.uOpacity,opacity);gl.uniform1i(instU.uKind,kind);gl.uniform1i(instU.uMaterial,material)}
function drawBatch(batch){gl.bindVertexArray(batch.vao);gl.drawElementsInstanced(gl.TRIANGLES,batch.indexCount,batch.indexType,0,batch.count);drawCalls++}
function drawParticleBatch(batch){gl.bindVertexArray(batch.vao);gl.drawArrays(gl.POINTS,0,batch.count);drawCalls++}
function drawLineBatch(batch,alpha){if(!batch.count)return;gl.useProgram(lineProgram);gl.uniformMatrix4fv(lineU.uViewProj,false,viewProj);gl.uniform1f(lineU.uAlpha,alpha);gl.bindVertexArray(batch.vao);gl.drawArrays(gl.LINES,0,batch.count);drawCalls++}
function drawBridges(){const ease=smoother(clamp((state.solar-.04)/.96,0,1)),central=islands[0];if(ease<.01)return;const baseStart=vadd(central.pos,v3(0,central.height*.37,0));for(let i=1;i<islands.length;i++){const dst=islands[i],fullEnd=vadd(dst.pos,v3(0,dst.height*.28,0)),end=vlerp(baseStart,fullEnd,ease),dir=vsub(fullEnd,baseStart),right=vnorm(vcross(v3(0,1,0),dir));for(const offset of [-1,0,1]){const off=vscale(right,11*offset),a=vadd(baseStart,off),b=vadd(end,off),model=mBasisBetween(a,b,offset===0?7.5:3.8,offset===0?2.5:1.7);drawMeshObject(solarBox,model,offset===0?.78:.92)}const nodePos=vlerp(baseStart,end,.93),nodeModel=mCompose(nodePos,[18*ease,18*ease,18*ease],state.time*.08+i*.4);drawMeshObject(ring,nodeModel,.58)}const crownPos=vadd(central.pos,v3(0,central.height*.62,0)),crownModel=mCompose(crownPos,[82*ease,82*ease,82*ease],state.time*.035);drawMeshObject(ring,crownModel,.58);const verticalA=mCompose(crownPos,[118*ease,118*ease,118*ease],state.time*.12,PI*.5,0),verticalB=mCompose(crownPos,[96*ease,96*ease,96*ease],state.time*.09+PI*.5,PI*.5,PI*.5);drawMeshObject(ring,verticalA,.48);drawMeshObject(ring,verticalB,.4)}

function drawTempestCrown(){const amp=state.tempest;if(amp<.02)return;const anchor=state.stormAnchor||islands[0],p=vadd(anchor.pos,v3(0,anchor.height*.24,0));for(let i=0;i<3;i++){const scale=(46+i*34)*amp,model=mCompose(p,[scale,scale,scale],state.time*(.3+i*.11)+i,PI*.5,i*PI/3);drawMeshObject(ring,model,.18+amp*.22)}}

function render(_alpha,t,delta){if(state.contextLost)return;resize();drawCalls=0;state.avgDelta=lerp(state.avgDelta,Math.min(.1,delta),.05);state.fps=1/Math.max(.001,state.avgDelta);if(state.frame%180===0){if(state.avgDelta>.024&&state.renderScale>.5){state.renderScale=Math.max(.5,state.renderScale-.08);resize();showToast(`Adaptive resolution ${Math.round(state.renderScale*100)}%`,1200)}else if(state.avgDelta<.0165&&state.renderScale<1){state.renderScale=Math.min(1,state.renderScale+.04);resize()}}
  gl.bindFramebuffer(gl.FRAMEBUFFER,targetFbo);gl.viewport(0,0,targetWidth,targetHeight);gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.useProgram(skyProgram);gl.uniform1f(skyU.uTime,t);gl.uniform1f(skyU.uTempest,state.tempest);gl.uniform1f(skyU.uSolar,state.solar);gl.uniform1f(skyU.uAspect,targetWidth/targetHeight);gl.uniform2f(skyU.uLook,Math.sin(camera.yaw)*.5,camera.pitch);gl.drawArrays(gl.TRIANGLES,0,3);drawCalls++;
  gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.clear(gl.DEPTH_BUFFER_BIT);gl.disable(gl.CULL_FACE);setMeshCommon();for(const island of islands){if(state.selected&&state.inspect>.04&&island===state.selected)continue;drawMeshObject(island.mesh,island.model,1)}for(const structure of structures)drawMeshObject(structure.mesh,structure.model,.96);drawBridges();drawTempestCrown();
  setInstCommon(0,1,1);drawBatch(vegetationBatch);setInstCommon(2,3,1);drawBatch(gliderBatch);
  gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.depthMask(false);setInstCommon(1,2,.7);drawBatch(crystalBatch);
  if(state.selected&&state.inspect>.02){setMeshCommon();const s=state.selected,corePos=vadd(s.pos,v3(0,-s.height*.38,0)),coreModel=mCompose(corePos,[24*state.inspect,40*state.inspect,24*state.inspect],state.time*.42+s.corePhase,state.time*.11);drawMeshObject(coreMesh,coreModel,.9);for(let i=0;i<3;i++){const rp=vadd(s.pos,v3(0,-s.height*(.18+i*.17),0)),rm=mCompose(rp,[s.radius*(.35+i*.11)*state.inspect,s.radius*(.35+i*.11)*state.inspect,s.radius*(.35+i*.11)*state.inspect],state.time*(.05+i*.02));drawMeshObject(ring,rm,.34)}gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);drawMeshObject(s.mesh,s.model,lerp(.82,.34,state.inspect));gl.depthMask(true)}
  gl.useProgram(particleProgram);gl.uniformMatrix4fv(particleU.uViewProj,false,viewProj);gl.uniform1f(particleU.uTime,t);gl.uniform1f(particleU.uPixelRatio,Math.min(devicePixelRatio||1,1.6)*state.renderScale);gl.uniform1f(particleU.uTempest,state.tempest);gl.uniform1f(particleU.uSolar,state.solar);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);drawParticleBatch(cloudBatch);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);drawParticleBatch(moteBatch);if(state.tempest>.01)drawParticleBatch(stormBatch);drawLineBatch(scanLines,state.inspect*.42);drawLineBatch(lightningLines,state.tempest*.9);gl.depthMask(true);gl.disable(gl.BLEND);
  gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,canvas.width,canvas.height);gl.disable(gl.DEPTH_TEST);gl.useProgram(postProgram);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,targetColor);gl.uniform1i(postU.uScene,0);gl.uniform2f(postU.uTexel,1/targetWidth,1/targetHeight);gl.uniform1f(postU.uTime,t);gl.uniform1f(postU.uTempest,state.tempest);gl.uniform1f(postU.uSolar,state.solar);gl.drawArrays(gl.TRIANGLES,0,3);drawCalls++;
  window.__AETHERIS_DIAGNOSTICS__={ready:true,webgl2:true,gpuRenderer:String(gpuRenderer),softwareRenderer,fps:Number(state.fps.toFixed(1)),renderScale:state.renderScale,drawCalls,particles:cloudBatch.count+moteBatch.count+stormBatch.count,instances:vegetationBatch.count+crystalBatch.count+gliderBatch.count,islands:islands.length,fieldVersion:field.version,tempest:Number(state.tempest.toFixed(3)),solar:Number(state.solar.toFixed(3)),inspection:!!state.selected,canvas:{width:canvas.width,height:canvas.height,clientWidth:canvas.clientWidth,clientHeight:canvas.clientHeight}};
}

function nearestIsland(){let nearest=islands[0],best=Infinity;for(const island of islands){const d=vlen(vsub(island.pos,camera.pos));if(d<best){best=d;nearest=island}}return{island:nearest,distance:best}}
function updateHud(){field.sample(camera.pos[0],camera.pos[2],fieldSample);const wind=Math.hypot(fieldSample[0],fieldSample[1]),near=nearestIsland();ui.field.textContent=clamp(fieldSample[2]+fieldSample[3]*.35,0,1.99).toFixed(2);ui.wind.textContent=wind.toFixed(1);ui.charge.textContent=Math.round(clamp(fieldSample[2],0,1)*100);ui.fps.textContent=Math.round(state.fps);const alt=Math.round(camera.pos[1]+520);ui.location.textContent=`${near.island.name} ${near.distance<260?'Airspace':'Vector'} · Altitude ${alt}m`;const deg=((camera.yaw/TAU*360)%360+360)%360;ui.bearing.textContent=`${deg<45||deg>=315?'N':deg<135?'E':deg<225?'S':'W'} ${String(Math.round(deg)).padStart(3,'0')}°`;const dist=vlen(vsub(camera.pos,islands[0].pos)),progress=clamp(1-dist/1200,0,1);ui.missionProgress.style.width=`${Math.round(progress*100)}%`;if(state.selected){field.sample(state.selected.pos[0],state.selected.pos[2],fieldSample);ui.scanFlux.textContent=(fieldSample[2]+fieldSample[3]*.2).toFixed(2);ui.scanCore.textContent=state.tempest>.5?'Overloaded':state.solar>.6?'Resonant':'Stable'}if(state.tempest>.35){ui.missionTitle.textContent='Ride the Tempest Shear';ui.missionBody.textContent='The storm is rewriting local routes. Hold altitude and watch the Crown lightning lattice.'}else if(state.solar>.55){ui.missionTitle.textContent='Cross the Solar Bridges';ui.missionBody.textContent='Ancient lightways are unfolding between islands. The geometry will persist after the surge.'}else{ui.missionTitle.textContent='Reach the Meridian Crown';ui.missionBody.textContent='Follow the cobalt current toward the central spire. Click any island to enter deep scan.'}}

function drawMap(){const w=mapCanvas.width,h=mapCanvas.height,ctx=mapCtx;ctx.clearRect(0,0,w,h);const grad=ctx.createRadialGradient(w*.5,h*.5,4,w*.5,h*.5,w*.72);grad.addColorStop(0,'rgba(18,64,76,.28)');grad.addColorStop(1,'rgba(2,9,15,.04)');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(153,225,239,.08)';ctx.lineWidth=1;for(let x=0;x<=w;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<=h;y+=25){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const mapPoint=(x,z)=>[w*.5+x/3000*w*.88,h*.5+z/3000*h*.88];ctx.strokeStyle=`rgba(109,244,255,${.18+state.solar*.22})`;ctx.lineWidth=.7;for(let gy=-2;gy<=2;gy++)for(let gx=-3;gx<=3;gx++){const x=gx*360,z=gy*400;field.sample(x,z,fieldSample);const [sx,sy]=mapPoint(x,z),mag=Math.hypot(fieldSample[0],fieldSample[1])||1;ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx+fieldSample[0]/mag*8,sy+fieldSample[1]/mag*8);ctx.stroke()}if(state.solar>.08){ctx.strokeStyle=`rgba(255,210,128,${state.solar*.32})`;for(let i=1;i<islands.length;i++){const a=mapPoint(islands[0].pos[0],islands[0].pos[2]),b=mapPoint(islands[i].pos[0],islands[i].pos[2]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}}for(const island of islands){const [x,y]=mapPoint(island.pos[0],island.pos[2]);ctx.beginPath();ctx.arc(x,y,clamp(island.radius/34,2.8,5),0,TAU);ctx.fillStyle=island===state.selected?'rgba(255,255,255,.42)':'rgba(4,24,31,.72)';ctx.fill();ctx.strokeStyle=island===state.selected?'rgba(255,255,255,.9)':'rgba(109,244,255,.64)';ctx.stroke()}const [cx,cy]=mapPoint(camera.pos[0],camera.pos[2]);ctx.save();ctx.translate(cx,cy);ctx.rotate(camera.yaw);ctx.fillStyle='#e9fbff';ctx.shadowColor='#aaf6ff';ctx.shadowBlur=7;ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(4,5);ctx.lineTo(0,3);ctx.lineTo(-4,5);ctx.closePath();ctx.fill();ctx.restore()}

canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();state.contextLost=true;loop.suspend();showBanner('CONTEXT LOST','REINITIALIZE THE TAB','RENDERER')});canvas.addEventListener('webglcontextrestored',()=>location.reload());
document.addEventListener('visibilitychange',()=>{if(document.hidden)loop.suspend();else loop.resume()});
addEventListener('beforeunload',()=>{loop.stop();audio?.ctx.close();destroyTargets()});

updateHud();drawMap();showToast(reducedMotion?'Reduced-motion flight law active':'Autopilot engaged · explore or take control',3000);
const loop=createFrameLoop({update,render,fixedStep:1/60,maxDelta:.08,maxSteps:4});loop.start();
})();
