(function(){
'use strict';
const $=s=>document.querySelector(s);const now=()=>new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());
const panel=$('#holo-status'),canvas=$('#world'),mission=$('#mission-chip'),onboarding=$('#onboarding'),telemetry=$('#telemetry'),settings=$('#settings');
const initialState={location:{district:'서울 북악 재난대응구역',subtitle:'도시 안전망 연결됨',coordinate:{x:0,z:20}},player:{hp:100,shield:76,energy:64,speed:0},resources:{credits:7450,data:320,kits:3},objectives:[{id:'center',title:'도시안전센터 접속',detail:'푸른 표식까지 도보 이동',progress:0,total:1,distance:86,status:'active',x:0,z:-66},{id:'relay',title:'북악 중계기 재가동',detail:'고가도로 아래 중계기 확인',progress:0,total:1,distance:128,status:'pending',x:-28,z:-108},{id:'archive',title:'지하 기록보관소 진입',detail:'관제동 후면 출입구 탐색',progress:0,total:1,distance:170,status:'pending',x:25,z:-148}],alerts:[{time:now(),category:'info',message:'WebGL2 현장 연결이 설정되었습니다.'},{time:now(),category:'quest',message:'도시안전센터 좌표를 수신했습니다.'}]};
const store=new HoloStore(initialState);panel.bind(store);
let uiScale=Number(localStorageSafe('kh-scale','1')),reduced=localStorageSafe('kh-motion','false')==='true',showTelemetry=localStorageSafe('kh-telemetry','true')!=='false';applyPrefs();
let lastStateUpdate=0;
let world;try{world=new KoreanWebGLWorld({canvas,onState:s=>{const t=performance.now();const st=store.getState();const objectives=st.objectives.map(o=>{if(!s.objective)return o;if(o.id===s.objective.id)return{...o,status:'active',distance:s.objective.distance};return o.status==='complete'?o:{...o,status:'pending'}});if(t-lastStateUpdate>90){lastStateUpdate=t;store.patch({location:{district:s.district,subtitle:s.running?'달리기 모드 // 생체 안정':'보행 동기화 // 도시망 정상',coordinate:{x:s.position.x,z:s.position.z}},player:{...st.player,speed:s.speed,energy:Math.max(20,Math.min(100,st.player.energy+(s.running?-.08:.025)))},objectives},{source:'world'})}renderHUD(s)},onEvent:e=>trigger(e,{autoOpen:e.category==='danger'}),onObjectiveComplete:o=>completeObjective(o)}).mount()}catch(error){console.error(error);document.body.classList.add('webgl-failed');onboarding.classList.remove('quiet');onboarding.querySelector('h1').textContent='WebGL2를 시작할 수 없습니다';onboarding.querySelector('p').textContent='WebGL2가 활성화된 최신 브라우저 또는 그래픽 드라이버에서 다시 실행하십시오.';throw error}
function renderHUD(s){const o=s.objective;$('#district-label').textContent=s.district;$('#objective-label').textContent=o?o.title:'주요 임무 완료';$('#objective-detail').textContent=o?o.detail:'현재 구역 안정화 완료';$('#objective-distance').textContent=o?`${Math.round(o.distance)}m`:'완료';mission.classList.toggle('complete',!o);$('#fps-readout').textContent=`${s.fps} FPS`;$('#speed-readout').textContent=`${s.speed.toFixed(1)} m/s`;$('#position-readout').textContent=`${Math.round(s.position.x)}, ${Math.round(s.position.z)}`;if(s.speed>.35)onboarding.classList.add('quiet')}
function addAlert(category,message){const s=store.getState();store.patch({alerts:[{time:now(),category,message},...(s.alerts||[])].slice(0,12)},{source:'event'})}
function trigger({category='info',title='도시망 알림',message='',icon},{autoOpen=false}={}){panel.setCategory(category);panel.notify({category,title,message,icon});addAlert(category,message);if(autoOpen)panel.show({category,mode:'standard'});flash(category)}
function completeObjective(o){const st=store.getState();const order=['center','relay','archive'],next=order[order.indexOf(o.id)+1];store.patch({objectives:st.objectives.map(x=>x.id===o.id?{...x,status:'complete',progress:x.total,distance:0}:x.id===next?{...x,status:'active'}:x),resources:{...st.resources,credits:st.resources.credits+250,data:st.resources.data+40}},{source:'objective-complete'});panel.show({category:'quest',mode:'standard'});panel.notify({category:'quest',title:'임무 단계 완료',message:`${o.title} 완료 // 도시 데이터 +40`,icon:'check',duration:5600});addAlert('quest',`${o.title} 완료. 다음 접근 좌표가 활성화되었습니다.`);flash('quest')}
function flash(category){document.body.dataset.flash=category;clearTimeout(flash.timer);flash.timer=setTimeout(()=>delete document.body.dataset.flash,440)}
function localStorageSafe(k,f){try{return localStorage.getItem(k)??f}catch{return f}}function save(k,v){try{localStorage.setItem(k,String(v))}catch{}}
function applyPrefs(){panel.style.setProperty('--holo-scale',uiScale);document.documentElement.dataset.reducedMotion=reduced?'true':'false';$('#scale-output').textContent=`${Math.round(uiScale*100)}%`;$('#ui-scale').value=uiScale;$('#reduce-motion').checked=reduced;$('#telemetry-toggle').checked=showTelemetry;telemetry.hidden=!showTelemetry}
function toggleSettings(force){const open=typeof force==='boolean'?force:!settings.classList.contains('open');settings.classList.toggle('open',open);settings.setAttribute('aria-hidden',String(!open));$('#settings-button').setAttribute('aria-expanded',String(open))}
function key(e){if(e.code==='KeyH'){panel.toggle({category:'info',mode:'standard'});onboarding.classList.add('quiet')}if(e.code==='Tab'){e.preventDefault();panel.setMode(panel.dataset.mode==='expanded'?'standard':'expanded').show()}if(e.code==='KeyQ')trigger({category:'quest',title:'임무 경로 갱신',message:'보행자 우선도로를 따라 다음 비콘으로 이동하십시오.',icon:'quest'});if(e.code==='KeyR')trigger({category:'danger',title:'위험 신호 감지',message:'전방 방재회랑에서 비인가 무인체가 감지되었습니다.',icon:'alert'},{autoOpen:true});if(e.code==='KeyE')trigger({category:'event',title:'북악 기상 교란',message:'산악권 자기장 변동으로 센서 오차가 증가합니다.',icon:'event'});if(e.code==='Escape'){panel.hide();toggleSettings(false)}}
window.addEventListener('keydown',key);document.addEventListener('visibilitychange',()=>document.hidden?world.suspend():world.resume());window.addEventListener('beforeunload',()=>world.destroy(),{once:true});
$('#toggle-panel').onclick=()=>panel.toggle({mode:'standard'});$('#quest-event').onclick=()=>trigger({category:'quest',title:'새 임무 수신',message:'북악 중계기 점검 순서가 갱신되었습니다.',icon:'quest'});$('#danger-event').onclick=()=>trigger({category:'danger',title:'위험 신호 감지',message:'전방 방재회랑에서 비인가 무인체가 감지되었습니다.',icon:'alert'},{autoOpen:true});$('#special-event').onclick=()=>trigger({category:'event',title:'특수 이벤트',message:'한강 북부권 전력망이 비상 모드로 전환됩니다.',icon:'event'});$('#settings-button').onclick=()=>toggleSettings();$('#settings-close').onclick=()=>toggleSettings(false);$('#reset-demo').onclick=()=>{world.reset();store.set(structuredClone(initialState));panel.hide();toggleSettings(false);onboarding.classList.remove('quiet')};$('#ui-scale').oninput=e=>{uiScale=Number(e.target.value);save('kh-scale',uiScale);applyPrefs()};$('#reduce-motion').onchange=e=>{reduced=e.target.checked;save('kh-motion',reduced);applyPrefs()};$('#telemetry-toggle').onchange=e=>{showTelemetry=e.target.checked;save('kh-telemetry',showTelemetry);applyPrefs()};
document.querySelectorAll('[data-move]').forEach(b=>{const d=b.dataset.move;const on=e=>{e.preventDefault();world.setMobileMove(d,true)},off=e=>{e.preventDefault();world.setMobileMove(d,false)};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});
window.__FORGE__={prepareVerification(scenario='default'){toggleSettings(false);world.reset();store.set(structuredClone(initialState));panel.hide();onboarding.classList.add('quiet');if(scenario==='panel-open')panel.show({category:'info',mode:'expanded'});if(scenario==='presentation'){onboarding.classList.add('quiet');panel.show({category:'info',mode:'standard'});}if(scenario==='danger')trigger({category:'danger',title:'검증 위험 알림',message:'위험 카테고리 자동 호출 검증',icon:'alert'},{autoOpen:true});return{ready:true,scenario,viewport:[innerWidth,innerHeight]}},verifyWorkflow(scenario='reference-case'){panel.hide();const before=panel.getSnapshot();panel.show({category:'quest',mode:'expanded'});panel.notify({category:'quest',title:'검증 임무',message:'알림 큐와 확장 상태 검증'});const after=panel.getSnapshot();return{scenario,pass:!before.open&&after.open&&after.mode==='expanded'&&after.notifications>0,checks:{startsClosed:!before.open,opensExpanded:after.open&&after.mode==='expanded',notificationQueued:after.notifications>0}}},verifyDomain(scenario='reference-case'){const s=world.getState(),b=KoreanWebGLWorld.WORLD_BOUNDS,inside=s.position.x>=b.minX&&s.position.x<=b.maxX&&s.position.z>=b.minZ&&s.position.z<=b.maxZ;return{scenario,claimLevel:'visual-concept',pass:s.renderer==='WebGL2'&&s.nearPlane===.08&&s.collisionCount>=8&&inside,checks:{webgl2Renderer:s.renderer==='WebGL2',nearPlaneClipping:s.nearPlane===.08,collisionVolumes:s.collisionCount,playerInsideBounds:inside,walkSpeed:KoreanWebGLWorld.WALK_SPEED},limitations:['절차적 저폴리 도시 데모이며 실제 서울 지형·교통 데이터를 재현하지 않습니다.','Unity·Unreal·Godot 네이티브 어댑터는 포함하지 않습니다.']}},reportFidelity(){return{renderer:'WebGL2',cssSize:[canvas.clientWidth,canvas.clientHeight],outputSize:[canvas.width,canvas.height],ratio:[canvas.width/canvas.clientWidth,canvas.height/canvas.clientHeight],nearPlane:.08,collisionVolumes:world.getState().collisionCount}},getSnapshot(){return{world:world.getState(),panel:panel.getSnapshot(),state:structuredClone(store.getState())}},teleportNearObjective(){return world.teleportNearObjective()},resetDemo(){world.reset();store.set(structuredClone(initialState));panel.hide();return true}};
setTimeout(()=>{onboarding.classList.add('quiet');panel.show({category:'info',mode:'standard'});panel.notify({category:'quest',title:'현장 임무 시작',message:'도시안전센터 비콘까지 도보로 이동하십시오.',icon:'quest',duration:6200})},700);
})();
