(function(global){
'use strict';
const V3={add:(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]],sub:(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],scale:(a,s)=>[a[0]*s,a[1]*s,a[2]*s],len:a=>Math.hypot(a[0],a[1],a[2]),norm:a=>{const l=Math.hypot(...a)||1;return[a[0]/l,a[1]/l,a[2]/l]},cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot:(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2]};
function perspective(out,fovy,aspect,near,far){const f=1/Math.tan(fovy/2),nf=1/(near-far);out.set([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);return out}
function lookAt(out,eye,center,up){let z=V3.norm(V3.sub(eye,center)),x=V3.norm(V3.cross(up,z)),y=V3.cross(z,x);out.set([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-V3.dot(x,eye),-V3.dot(y,eye),-V3.dot(z,eye),1]);return out}
function multiply(out,a,b){const r=new Float32Array(16);for(let c=0;c<4;c++)for(let row=0;row<4;row++)r[c*4+row]=a[0*4+row]*b[c*4+0]+a[1*4+row]*b[c*4+1]+a[2*4+row]*b[c*4+2]+a[3*4+row]*b[c*4+3];out.set(r);return out}
function modelMatrix(x,y,z,sx,sy,sz,ry=0,rx=0,rz=0){const cy=Math.cos(ry),syy=Math.sin(ry),cx=Math.cos(rx),sxx=Math.sin(rx),cz=Math.cos(rz),szz=Math.sin(rz);const m=new Float32Array(16);const r00=cy*cz+syy*sxx*szz,r01=-cy*szz+syy*sxx*cz,r02=syy*cx;const r10=cx*szz,r11=cx*cz,r12=-sxx;const r20=-syy*cz+cy*sxx*szz,r21=syy*szz+cy*sxx*cz,r22=cy*cx;m.set([r00*sx,r10*sx,r20*sx,0,r01*sy,r11*sy,r21*sy,0,r02*sz,r12*sz,r22*sz,0,x,y,z,1]);return m}
function hex(h,a=1){h=h.replace('#','');if(h.length===3)h=h.split('').map(c=>c+c).join('');return[parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255,a]}
function compile(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
function program(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,compile(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,compile(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p}
function mesh(gl,data){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const vbo=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vbo);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data.vertices),gl.STATIC_DRAW);const stride=8*4;for(const [i,n,o] of [[0,3,0],[1,3,3],[2,2,6]]){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,n,gl.FLOAT,false,stride,o*4)}const ibo=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ibo);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(data.indices),gl.STATIC_DRAW);gl.bindVertexArray(null);return{vao,count:data.indices.length}}
function cubeData(){const v=[],i=[];const faces=[[[0,0,1],[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]],[[0,0,-1],[.5,-.5,-.5],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5]],[[1,0,0],[.5,-.5,.5],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5]],[[-1,0,0],[-.5,-.5,-.5],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5]],[[0,1,0],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5],[-.5,.5,-.5]],[[0,-1,0],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5],[-.5,-.5,.5]]];for(let f=0;f<faces.length;f++){const [n,...p]=faces[f],base=v.length/8,uv=[[0,0],[1,0],[1,1],[0,1]];p.forEach((q,k)=>v.push(...q,...n,...uv[k]));i.push(base,base+1,base+2,base,base+2,base+3)}return{vertices:v,indices:i}}
function quadData(){return{vertices:[-.5,-.5,0,0,0,1,0,0,.5,-.5,0,0,0,1,1,0,.5,.5,0,0,0,1,1,1,-.5,.5,0,0,0,1,0,1],indices:[0,1,2,0,2,3]}}
function cylinderData(seg=12){const v=[],i=[];for(let y=0;y<=1;y++)for(let s=0;s<=seg;s++){const a=s/seg*Math.PI*2,x=Math.cos(a)*.5,z=Math.sin(a)*.5;v.push(x,y-.5,z,x,0,z,s/seg,y)}for(let s=0;s<seg;s++){const a=s,b=s+1,c=s+seg+1,d=c+1;i.push(a,c,b,b,c,d)}const top=v.length/8;v.push(0,.5,0,0,1,0,.5,.5);const bot=top+1;v.push(0,-.5,0,0,-1,0,.5,.5);for(let s=0;s<seg;s++){const a=s+seg+1,b=s+seg+2;i.push(top,a,b);i.push(bot,s+1,s)}return{vertices:v,indices:i}}
function coneData(seg=8){const v=[],i=[];for(let s=0;s<=seg;s++){const a=s/seg*Math.PI*2,x=Math.cos(a)*.5,z=Math.sin(a)*.5,n=V3.norm([x,.35,z]);v.push(x,-.5,z,...n,s/seg,0);v.push(0,.5,0,...n,s/seg,1)}for(let s=0;s<seg;s++){const b=s*2;i.push(b,b+2,b+1,b+2,b+3,b+1)}return{vertices:v,indices:i}}
function signTexture(gl,text,sub='',accent='#54e5ff',wide=512,tall=160){const c=document.createElement('canvas');c.width=wide;c.height=tall;const x=c.getContext('2d');x.clearRect(0,0,wide,tall);x.fillStyle='rgba(3,14,18,.90)';x.fillRect(0,0,wide,tall);x.strokeStyle=accent;x.lineWidth=5;x.strokeRect(7,7,wide-14,tall-14);x.fillStyle=accent;x.fillRect(0,0,13,tall);x.font='700 48px "Noto Sans KR",sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(text,wide/2,tall*.43);if(sub){x.font='500 22px ui-monospace,monospace';x.fillStyle='rgba(235,252,255,.68)';x.fillText(sub,wide/2,tall*.74)}const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,c);gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return t}
class KoreanWebGLWorld{
 static WALK_SPEED=4.2; static RUN_SPEED=7.2; static WORLD_BOUNDS={minX:-72,maxX:72,minZ:-185,maxZ:30};
 constructor({canvas,onState,onEvent,onObjectiveComplete}){this.canvas=canvas;this.onState=onState||(()=>{});this.onEvent=onEvent||(()=>{});this.onObjectiveComplete=onObjectiveComplete||(()=>{});this.keys=new Set();this.mobile=new Set();this.pos=[0,1.72,20];this.vel=[0,0,0];this.yaw=0;this.pitch=-.035;this.running=false;this.last=performance.now();this.samples=[];this.fps=60;this.frameP95=16.7;this.renderScale=1;this.suspended=false;this.objectives=[{id:'center',title:'도시안전센터 접속',detail:'푸른 표식까지 도보 이동',x:0,z:-66,status:'active'},{id:'relay',title:'북악 중계기 재가동',detail:'고가도로 아래 중계기 확인',x:-28,z:-108,status:'pending'},{id:'archive',title:'지하 기록보관소 진입',detail:'관제동 후면 출입구 탐색',x:25,z:-148,status:'pending'}];this.activeIndex=0;this.collisions=[];this.objects=[];this.transparent=[];this.eventFlags=new Set()}
 mount(){this.gl=this.canvas.getContext('webgl2',{antialias:true,alpha:true,powerPreference:'high-performance'});if(!this.gl)throw new Error('WebGL2를 지원하는 브라우저가 필요합니다.');this.initGL();this.buildWorld();this.bindInput();this.resize();this.loop=this.loop.bind(this);this.raf=requestAnimationFrame(this.loop);return this}
 initGL(){const gl=this.gl;const vs=`#version 300 es\nprecision highp float;layout(location=0)in vec3 aPosition;layout(location=1)in vec3 aNormal;layout(location=2)in vec2 aUV;uniform mat4 uModel;uniform mat4 uViewProj;out vec3 vNormal;out vec3 vWorld;out vec2 vUV;void main(){vec4 w=uModel*vec4(aPosition,1.0);vWorld=w.xyz;vNormal=normalize(mat3(uModel)*aNormal);vUV=aUV;gl_Position=uViewProj*w;}`;const fs=`#version 300 es\nprecision highp float;in vec3 vNormal;in vec3 vWorld;in vec2 vUV;uniform vec4 uColor;uniform vec3 uCamera;uniform vec3 uSun;uniform vec3 uFog;uniform float uFogNear;uniform float uFogFar;uniform float uEmissive;uniform bool uUseTexture;uniform sampler2D uTexture;out vec4 outColor;void main(){vec4 base=uUseTexture?texture(uTexture,vUV)*uColor:uColor;if(base.a<.02)discard;float nd=max(dot(normalize(vNormal),normalize(uSun)),0.0);float light=.34+nd*.70+uEmissive;vec3 col=base.rgb*light;float d=distance(vWorld,uCamera);float fog=smoothstep(uFogNear,uFogFar,d);col=mix(col,uFog,fog);outColor=vec4(col,base.a*(1.0-fog*.32));}`;this.prog=program(gl,vs,fs);this.loc={model:gl.getUniformLocation(this.prog,'uModel'),vp:gl.getUniformLocation(this.prog,'uViewProj'),color:gl.getUniformLocation(this.prog,'uColor'),camera:gl.getUniformLocation(this.prog,'uCamera'),sun:gl.getUniformLocation(this.prog,'uSun'),fog:gl.getUniformLocation(this.prog,'uFog'),fogNear:gl.getUniformLocation(this.prog,'uFogNear'),fogFar:gl.getUniformLocation(this.prog,'uFogFar'),emissive:gl.getUniformLocation(this.prog,'uEmissive'),useTexture:gl.getUniformLocation(this.prog,'uUseTexture'),texture:gl.getUniformLocation(this.prog,'uTexture')};this.meshes={cube:mesh(gl,cubeData()),quad:mesh(gl,quadData()),cylinder:mesh(gl,cylinderData(12)),cone:mesh(gl,coneData(9))};gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);this.projection=new Float32Array(16);this.view=new Float32Array(16);this.viewProj=new Float32Array(16)}
 add(kind,x,y,z,sx,sy,sz,color,opts={}){const o={mesh:this.meshes[kind],model:modelMatrix(x,y,z,sx,sy,sz,opts.ry||0,opts.rx||0,opts.rz||0),color:hex(color,opts.alpha??1),texture:opts.texture||null,emissive:opts.emissive||0,transparent:(opts.alpha??1)<1||!!opts.texture};(o.transparent?this.transparent:this.objects).push(o);if(opts.collision)this.collisions.push({minX:x-sx/2,maxX:x+sx/2,minZ:z-sz/2,maxZ:z+sz/2});return o}
 sign(text,sub,x,y,z,w,h,accent='#54e5ff',ry=0){const tex=signTexture(this.gl,text,sub,accent);return this.add('quad',x,y,z,w,h,1,'#ffffff',{texture:tex,emissive:.42,ry,alpha:1})}
 buildWorld(){const A=(...a)=>this.add(...a);A('cube',0,-.4,-76,150,.8,235,'#5b625f');A('cube',0,.015,-76,14,.03,225,'#252d30');A('cube',-9,.11,-76,4,.22,225,'#7a7f7d');A('cube',9,.11,-76,4,.22,225,'#7a7f7d');A('cube',-7.05,.2,-76,.22,.35,225,'#c5c8be');A('cube',7.05,.2,-76,.22,.35,225,'#c5c8be');A('cube',-10.2,.24,-76,1.05,.25,225,'#d5b734');A('cube',10.2,.24,-76,1.05,.25,225,'#d5b734');for(let z=20;z>-180;z-=11){A('cube',-2.4,.05,z,.13,.04,4.6,'#e9e9de');A('cube',2.4,.05,z,.13,.04,4.6,'#e9e9de')}for(let x=-5.2;x<=5.2;x+=1.15)A('cube',x,.07,-23,.72,.04,5.3,'#efeee5');A('cube',-4.9,.08,-76,.16,.05,225,'#3e85a5');
 const mountain=[[-68,-242,68,64,58],[-25,-255,90,72,62],[32,-250,78,59,60],[76,-245,65,68,55],[-100,-255,55,52,45],[110,-260,70,60,55]];mountain.forEach(([x,z,sx,sy,sz],i)=>A('cone',x,sy/2-2,z,sx,sy,sz,i%2?'#4d5558':'#596164',{ry:i*.33}));
 const building=(x,z,w,h,d,c,signInfo)=>{A('cube',x,h/2,z,w,h,d,c,{collision:true});A('cube',x,h+.45,z,w*.45,.9,d*.45,'#39464b');if(signInfo)this.sign(signInfo[0],signInfo[1],x,h*.68,z+d/2+.03,w*.72,2.3,signInfo[2]||'#54e5ff')};
 building(-21,-38,20,7.2,17,'#4d5d61',['서울 도시안전센터','SEOUL SAFE CITY 01','#54e5ff']);A('cube',-21,1.15,-29.45,7,2.3,.2,'#24383e');A('cube',-27.4,4.2,-29.48,4.2,1.4,.18,'#9da7a5');
 building(20,-29,15,5.7,13,'#51585a',['편의점 24','무인 재난보급소','#65f1a5']);A('cube',20,1.5,-22.42,11,2.7,.12,'#16323a');
 building(26,-62,14,9,18,'#4f5a5e',['북악 생활안전관','COMMUNITY SHELTER','#ffae36']);
 const tower=(x,z,w,h,d,c)=>{building(x,z,w,h,d,c);for(let yy=5;yy<h-2;yy+=4.2){for(let xx=-w*.34;xx<=w*.34;xx+=w*.23)A('cube',x+xx,yy,z+d/2+.03,w*.12,1.25,.08,yy%8<4?'#b5c7c7':'#cfb27e',{emissive:.08})}A('cube',x,h+1.1,z,w*.18,2.2,d*.18,'#303b3e')};
 tower(-38,-88,18,42,18,'#606a6b');tower(-60,-112,16,50,16,'#566163');tower(42,-96,18,46,18,'#5e686a');tower(62,-128,16,56,16,'#515c5e');tower(-44,-152,20,39,18,'#596466');tower(38,-165,22,44,20,'#596265');
 building(0,-132,26,22,25,'#46565a',['북악 재난관제동','BUKAK RESILIENCE CONTROL','#54e5ff']);A('cube',0,29,-132,5,14,5,'#34464b');A('cube',0,37,-132,1.2,3,1.2,'#7bdff1',{emissive:.4});
 for(let z=10;z>-175;z-=22){for(const side of[-1,1]){const x=side*8.25;A('cylinder',x,2.9,z,.18,5.8,.18,'#39494d');A('cube',x-side*.55,5.72,z,1.25,.12,.14,'#39494d');A('cube',x-side*1.1,5.62,z,.42,.17,.42,'#dbf7ed',{emissive:.62});}}
 for(const [x,z] of [[-11,-12],[11,-8],[-12,-53],[12,-47],[-12,-92],[12,-102],[-11,-137],[11,-145]]){A('cylinder',x,1.2,z,.34,2.4,.34,'#66513a');A('cone',x,4.1,z,3.5,5.9,3.5,'#2d493a');A('cone',x+.4,5.4,z-.2,2.8,4.4,2.8,'#355343')}
 A('cube',10.5,2.5,-49,4.8,.22,2.4,'#779095',{alpha:.78});A('cylinder',8.6,1.3,-49,.13,2.6,.13,'#405156');A('cylinder',12.4,1.3,-49,.13,2.6,.13,'#405156');A('cube',10.5,.52,-49,3.7,.25,.7,'#4f5e61');this.sign('버스 정류장','북악안전센터 · 02137',10.5,2.02,-47.76,3.8,.9,'#54e5ff');
 A('cube',0,5.2,-74,16,.7,.7,'#3b494d');A('cylinder',-7.2,2.6,-74,.35,5.2,.35,'#3b494d');A('cylinder',7.2,2.6,-74,.35,5.2,.35,'#3b494d');this.sign('북악 재난대응구역','속도 30 · 보행자 우선',0,5.2,-73.62,11.5,2.4,'#54e5ff');
 for(const x of[-5.7,5.7]){A('cylinder',x,2.4,-22,.22,4.8,.22,'#353f42');A('cube',x,4.7,-22,.8,.35,.65,'#232b2d');A('cube',x,4.78,-21.64,.19,.19,.08,'#70ef9e',{emissive:.55})}
 for(let z=-5;z>-165;z-=16)for(const x of[-6.65,6.65])A('cylinder',x,.45,z,.22,.9,.22,'#5f7073');
 const barrierZ=-101;for(const x of[-6,-4,-2,2,4,6])A('cube',x,.55,barrierZ,1.2,1.1,.55,'#d8c23c');
 this.sign('세종로 12길','SEJONG-RO 12-GIL',-11,3.4,-15.4,5.2,1.25,'#3b8cff',Math.PI/2);
 for(let i=0;i<13;i++){const x=-65+i*11,z=-190-(i%3)*7,h=10+(i%5)*3;A('cube',x,h/2,z,8,h,8,i%2?'#50595a':'#5b6464')}
 this.beaconObjects=[];for(let k=0;k<4;k++){const o=A('cube',0,2.4+k*.8,-66,.09,4.6-k*.6,.09,'#54e5ff',{alpha:.48,emissive:.8});this.beaconObjects.push(o)}A('cube',0,.12,-66,3.7,.08,3.7,'#54e5ff',{alpha:.25,emissive:.8,ry:Math.PI/4});
 }
 bindInput(){this.onKeyDown=e=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code)){this.keys.add(e.code);if(e.code.startsWith('Arrow'))e.preventDefault()}};this.onKeyUp=e=>this.keys.delete(e.code);this.onMouse=e=>{if(document.pointerLockElement===this.canvas){this.yaw-=e.movementX*.00225;this.pitch=clamp(this.pitch-e.movementY*.0019,-1.12,1.05)}};this.onClick=()=>{if(document.pointerLockElement!==this.canvas)this.canvas.requestPointerLock?.()};this.canvas.addEventListener('click',this.onClick);window.addEventListener('keydown',this.onKeyDown);window.addEventListener('keyup',this.onKeyUp);window.addEventListener('mousemove',this.onMouse);let dragging=false,lastX=0,lastY=0;this.canvas.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY});window.addEventListener('pointerup',()=>dragging=false);this.canvas.addEventListener('pointermove',e=>{if(dragging&&document.pointerLockElement!==this.canvas){this.yaw-=(e.clientX-lastX)*.004;this.pitch=clamp(this.pitch-(e.clientY-lastY)*.003,-1.12,1.05);lastX=e.clientX;lastY=e.clientY}});this.onResize=()=>this.resize();window.addEventListener('resize',this.onResize)}
 setMobileMove(dir,on){on?this.mobile.add(dir):this.mobile.delete(dir)}
 key(...codes){return codes.some(c=>this.keys.has(c))}
 update(dt,t){const forward=this.key('KeyW','ArrowUp')||this.mobile.has('forward'),back=this.key('KeyS','ArrowDown')||this.mobile.has('back'),left=this.key('KeyA','ArrowLeft')||this.mobile.has('left'),right=this.key('KeyD','ArrowRight')||this.mobile.has('right');let ix=(right?1:0)-(left?1:0),iz=(forward?1:0)-(back?1:0);const mag=Math.hypot(ix,iz)||1;ix/=mag;iz/=mag;this.running=this.key('ShiftLeft','ShiftRight')&&(forward||back||left||right);const speed=this.running?KoreanWebGLWorld.RUN_SPEED:KoreanWebGLWorld.WALK_SPEED;const fx=Math.sin(this.yaw),fz=-Math.cos(this.yaw),rx=Math.cos(this.yaw),rz=Math.sin(this.yaw);const tx=(fx*iz+rx*ix)*speed,tz=(fz*iz+rz*ix)*speed;const response=1-Math.exp(-dt*10);this.vel[0]+=(tx-this.vel[0])*response;this.vel[2]+=(tz-this.vel[2])*response;if(!forward&&!back&&!left&&!right){this.vel[0]*=Math.exp(-dt*8);this.vel[2]*=Math.exp(-dt*8)}this.moveAxis(0,this.vel[0]*dt);this.moveAxis(2,this.vel[2]*dt);this.pos[0]=clamp(this.pos[0],KoreanWebGLWorld.WORLD_BOUNDS.minX,KoreanWebGLWorld.WORLD_BOUNDS.maxX);this.pos[2]=clamp(this.pos[2],KoreanWebGLWorld.WORLD_BOUNDS.minZ,KoreanWebGLWorld.WORLD_BOUNDS.maxZ);const active=this.objectives[this.activeIndex];if(active){const d=Math.hypot(active.x-this.pos[0],active.z-this.pos[2]);active.distance=d;if(d<5.5){active.status='complete';this.onObjectiveComplete({...active});this.activeIndex++;if(this.objectives[this.activeIndex])this.objectives[this.activeIndex].status='active';this.moveBeacon()}if(d<28&&active.id==='relay'&&!this.eventFlags.has('relay-danger')){this.eventFlags.add('relay-danger');this.onEvent({category:'danger',title:'무인 감시체 접근',message:'고가도로 하부에서 비인가 열원이 감지되었습니다.'})}}if(this.pos[2]<-120&&!this.eventFlags.has('event')){this.eventFlags.add('event');this.onEvent({category:'event',title:'북악 자기장 교란',message:'관제동 주변 센서 정확도가 일시적으로 저하됩니다.'})}const walk=Math.hypot(this.vel[0],this.vel[2]);const bob=Math.sin(t*.012*(this.running?1.5:1))*Math.min(.045,walk*.006);this.pos[1]=1.72+bob}
 moveAxis(axis,amount){if(!amount)return;const next=[...this.pos];next[axis]+=amount;const r=.36;for(const c of this.collisions){if(next[0]+r>c.minX&&next[0]-r<c.maxX&&next[2]+r>c.minZ&&next[2]-r<c.maxZ)return}this.pos[axis]=next[axis]}
 moveBeacon(){const active=this.objectives[this.activeIndex];if(!active){this.beaconObjects.forEach(o=>o.color[3]=0);return}this.beaconObjects.forEach((o,k)=>{o.model=modelMatrix(active.x,2.4+k*.8,active.z,.09,4.6-k*.6,.09,0);o.color[3]=.48})}
 render(t){const gl=this.gl;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const aspect=this.canvas.width/this.canvas.height;perspective(this.projection,68*Math.PI/180,aspect,.08,430);const cp=Math.cos(this.pitch),dir=[Math.sin(this.yaw)*cp,Math.sin(this.pitch),-Math.cos(this.yaw)*cp];const center=V3.add(this.pos,dir);lookAt(this.view,this.pos,center,[0,1,0]);multiply(this.viewProj,this.projection,this.view);gl.useProgram(this.prog);gl.uniformMatrix4fv(this.loc.vp,false,this.viewProj);gl.uniform3fv(this.loc.camera,this.pos);gl.uniform3fv(this.loc.sun,V3.norm([-.45,.82,.28]));gl.uniform3fv(this.loc.fog,[.48,.56,.59]);gl.uniform1f(this.loc.fogNear,68);gl.uniform1f(this.loc.fogFar,310);this.drawList(this.objects,false);gl.depthMask(false);this.drawList(this.transparent,true,t);gl.depthMask(true)}
 drawList(list,transparent,t=0){const gl=this.gl;for(let idx=0;idx<list.length;idx++){const o=list[idx];if(this.beaconObjects?.includes(o)){const active=this.objectives[this.activeIndex];if(active){const k=this.beaconObjects.indexOf(o);o.model=modelMatrix(active.x+Math.sin(t*.0017+k)*.55,2.2+k*.8,active.z+Math.cos(t*.0014+k)*.55,.1,4.8-k*.55,.1,t*.0005+k);o.color[3]=.3+.18*Math.sin(t*.003+k)}}gl.bindVertexArray(o.mesh.vao);gl.uniformMatrix4fv(this.loc.model,false,o.model);gl.uniform4fv(this.loc.color,o.color);gl.uniform1f(this.loc.emissive,o.emissive);gl.uniform1i(this.loc.useTexture,!!o.texture);if(o.texture){gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,o.texture);gl.uniform1i(this.loc.texture,0)}gl.drawElements(gl.TRIANGLES,o.mesh.count,gl.UNSIGNED_SHORT,0)}}
 resize(){const dpr=Math.min(1.45,devicePixelRatio||1)*this.renderScale;const w=Math.max(1,Math.round(this.canvas.clientWidth*dpr)),h=Math.max(1,Math.round(this.canvas.clientHeight*dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}}
 loop(now){if(this.suspended)return;const dt=Math.min(.05,(now-this.last)/1000||.016);this.last=now;this.samples.push(dt*1000);if(this.samples.length>180)this.samples.shift();if(now-(this._metricTime||0)>650){this._metricTime=now;const s=[...this.samples].sort((a,b)=>a-b);this.frameP95=s[Math.max(0,Math.ceil(s.length*.95)-1)]||16.7;this.fps=Math.round(1000/((this.samples.reduce((a,b)=>a+b,0)/this.samples.length)||16.7));if(this.frameP95>27&&this.renderScale>.76){this.renderScale=Math.max(.76,this.renderScale-.08);this.resize()}}this.update(dt,now);this.render(now);const a=this.objectives[this.activeIndex];this.onState({position:{x:this.pos[0],z:this.pos[2]},speed:Math.hypot(this.vel[0],this.vel[2]),running:this.running,fps:this.fps,frameP95:this.frameP95,district:this.pos[2]<-118?'북악 관제구역':this.pos[2]<-65?'세종 방재회랑':'서울 북악 재난대응구역',objective:a?{...a}:null,renderer:'WebGL2',nearPlane:.08});this.raf=requestAnimationFrame(this.loop)}
 reset(){this.pos=[0,1.72,20];this.vel=[0,0,0];this.yaw=0;this.pitch=-.035;this.activeIndex=0;this.objectives.forEach((o,i)=>o.status=i===0?'active':'pending');this.eventFlags.clear();this.moveBeacon()}
 teleportNearObjective(){const a=this.objectives[this.activeIndex];if(a){this.pos[0]=a.x;this.pos[2]=a.z+7}return this.getState()}
 suspend(){if(this.suspended)return;this.suspended=true;cancelAnimationFrame(this.raf)}
 resume(){if(!this.suspended)return;this.suspended=false;this.last=performance.now();this.raf=requestAnimationFrame(this.loop)}
 destroy(){cancelAnimationFrame(this.raf);window.removeEventListener('keydown',this.onKeyDown);window.removeEventListener('keyup',this.onKeyUp);window.removeEventListener('mousemove',this.onMouse);window.removeEventListener('resize',this.onResize);this.canvas.removeEventListener('click',this.onClick)}
 getState(){const a=this.objectives[this.activeIndex];return{position:{x:this.pos[0],y:this.pos[1],z:this.pos[2]},speed:Math.hypot(this.vel[0],this.vel[2]),yaw:this.yaw,pitch:this.pitch,objective:a?{...a}:null,fps:this.fps,frameP95:this.frameP95,nearPlane:.08,collisionCount:this.collisions.length,renderer:'WebGL2'}}
}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
global.KoreanWebGLWorld=KoreanWebGLWorld;
})(window);
