#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const args=process.argv.slice(2), input=args.find(a=>!a.startsWith('--'));
if(!input){console.error('Usage: node scripts/fidelity_audit.mjs <entry.html> [--flagship] [--out report.json]');process.exit(2);}
const flagship=args.includes('--flagship'), oi=args.indexOf('--out'), outPath=oi>=0?path.resolve(args[oi+1]):null;
const inputPath=path.resolve(input), file=fs.statSync(inputPath).isDirectory()?path.join(inputPath,'index.html'):inputPath;
const projectRoot=fs.statSync(inputPath).isDirectory()?inputPath:path.dirname(file);
const JS_SCRIPT_TYPE_RE=/^(?:text\/javascript|application\/javascript|application\/ecmascript|text\/ecmascript|module)$/i;
const IMPORT_REF_RE=/(?:import\s*(?:[^"']*?\sfrom\s*)?|export\s+[^"']*?\sfrom\s*|import\s*\()\s*["']([^"']+)["']/g;
const visited=new Set(),sourceFiles=[],queue=[file];
while(queue.length){const current=queue.shift();if(!current||visited.has(current)||!fs.existsSync(current)||!fs.statSync(current).isFile())continue;if(!current.startsWith(projectRoot+path.sep)&&current!==file)continue;visited.add(current);const source=fs.readFileSync(current,'utf8');sourceFiles.push({file:current,source});const refs=[];if(/\.html?$/i.test(current)){for(const m of source.matchAll(/<(?:script|link)\b[^>]*(?:src|href)\s*=\s*["']([^"']+)["'][^>]*>/gi))refs.push(m[1]);for(const m of source.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){const attrs=m[1]||'';if(/\bsrc\s*=/i.test(attrs))continue;const tm=attrs.match(/\btype\s*=\s*["']([^"']+)["']/i),type=tm?tm[1].trim():'';if(type&&!JS_SCRIPT_TYPE_RE.test(type))continue;for(const r of m[2].matchAll(IMPORT_REF_RE))refs.push(r[1]);}}if(/\.[mc]?js$/i.test(current))for(const m of source.matchAll(IMPORT_REF_RE))refs.push(m[1]);for(const ref of refs){if(!ref||ref.startsWith('#')||ref.startsWith('//')||/^[a-z][a-z0-9+.-]*:/i.test(ref))continue;const clean=ref.split(/[?#]/)[0],resolved=ref.startsWith('/')?path.resolve(projectRoot,clean.replace(/^\/+/,'')):path.resolve(path.dirname(current),clean);if(resolved.startsWith(projectRoot+path.sep)&&!visited.has(resolved))queue.push(resolved);}}
const entryText=sourceFiles.find(i=>i.file===file)?.source||'', text=sourceFiles.map(i=>i.source).join('\n'), compact=text.replace(/\s+/g,' '),findings=[];
const add=(id,severity,detail)=>findings.push({id,severity,detail});
const scaleExpression=compact.match(/renderScale\s*:\s*([^,}]+)/i)?.[1]||'', likely=[...scaleExpression.matchAll(/(?:0?\.\d+)/g)].map(m=>Number(m[0])).filter(v=>v>0&&v<=1.5);
const hasReconstruction=/resolve[-_ ]?pass|upscal|sharpen|rcas|easu|fsr|smaa|fxaa|taa|post[-_ ]?chain/i.test(compact),hasCaptureLock=/captureMode|capturePreset|presentationPreset|lockQuality|adaptiveLocked|captureLocked/i.test(compact),hasAdaptive=/sceneScale|renderScale|adaptiveFloor|adaptiveCeiling|resolutionPolicy|setSize\([^)]*(?:scale|ratio)/i.test(compact);
const ceilings=[...compact.matchAll(/renderScale\s*<\s*(0?\.\d+)|Math\.min\(\s*(0?\.\d+)\s*,\s*state\.renderScale/gi)].map(m=>Number(m[1]||m[2])).filter(Number.isFinite),ceiling=ceilings.length?Math.max(...ceilings):null;
if(likely.length&&Math.max(...likely)<.85&&!hasReconstruction)add('low-default-scene-density',flagship?'error':'warning',`renderScale candidates ${JSON.stringify(likely)} remain below 0.85 without reconstruction`);
if(ceiling!==null&&ceiling<.9)add('low-adaptive-ceiling',flagship?'error':'warning',`adaptive resolution ceiling appears to be ${ceiling}`);
if(/test/i.test(scaleExpression)&&likely.some(v=>v<.6)&&!hasCaptureLock)add('test-capture-quality-coupling',flagship?'error':'warning','test mode appears to lower render quality without independent presentation capture lock');
if(/antialias\s*:\s*false/i.test(compact)&&!hasReconstruction)add('no-explicit-resolve','warning','antialiasing is disabled and no resolve/reconstruction stage was detected');
if(/grain.{0,100}gl_FragCoord|hash\w*\(frag/i.test(compact)&&likely.some(v=>v<.9)&&!hasReconstruction)add('high-frequency-before-upscale','warning','grain/scanline-like high-frequency detail is generated in the low-resolution scene pass rather than native output space');
const buttonBodies=[...entryText.matchAll(/<button\b[^>]*>([\s\S]*?)<\/button>/gi)].map(m=>m[1].trim()),unicodeButtons=buttonBodies.filter(body=>{if(!body||/<svg\b/i.test(body)||/<img\b/i.test(body))return false;const s=body.replace(/<[^>]+>/g,'').trim();return s.length>0&&s.length<=8&&!/[A-Za-z0-9가-힣]/.test(s);});
if(unicodeButtons.length)add('unicode-icon-placeholders',flagship?'error':'warning',`${unicodeButtons.length} button(s) use text symbols instead of an authored icon system`);
// Do NOT infer look direction from yaw +=/-= mouse delta. Euler signs are renderer-specific.
if(/pointerLock|movementX|pointermove/i.test(compact)&&!/getInputProbeState|verifyPointerDirection|semanticYaw|directionReviewed|pointer_direction_review/i.test(compact))add('pointer-semantic-direction-unverified','warning','pointer look exists but no semantic runtime/view-basis direction evidence was detected; numeric yaw sign alone is not proof');
if(/pointerLock/i.test(compact)&&!/invertX|invertY|setInversion|directionReviewed/i.test(compact))add('pointer-direction-contract-missing','warning','pointer look exists but no explicit inversion/direction contract was detected');
const worldSize=Number(compact.match(/\bWORLD_SIZE\s*=\s*(\d+(?:\.\d+)?)/i)?.[1]), areaMatch=text.match(/(\d+(?:\.\d+)?)\s*km\s*(?:²|2)/i), displayedArea=Number(areaMatch?.[1]), meterSemantics=/(?:--|distance|거리|alt|coordinates?).{0,80}\bm\b|\b\d+(?:\.\d+)?\s*m\b/i.test(compact);let computed=null;
if(Number.isFinite(worldSize)&&Number.isFinite(displayedArea)&&meterSemantics){computed=worldSize*worldSize/1e6;const err=Math.abs(displayedArea-computed)/Math.max(computed,1e-9);if(err>.1)add('displayed-world-area-mismatch',flagship?'error':'warning',`displayed area ${displayedArea} km² does not match WORLD_SIZE bounding area ${computed.toFixed(4)} km²`);}
const hasWebGL=/getContext\(\s*['"]webgl2?/i.test(compact);if(hasWebGL&&!/webglcontextlost/i.test(compact))add('webgl-context-loss-unhandled','warning','WebGL is used but no context-loss handler was detected');if(hasWebGL&&!/beforeunload|pagehide|destroy\s*\(|dispose\s*\(/i.test(compact))add('runtime-disposal-missing','warning','no explicit lifecycle/disposal path detected');if(/prefers-reduced-motion/i.test(compact)&&!/motionScale|reducedMotion|reduceMotion|worldMotion/i.test(compact))add('css-only-reduced-motion','warning','reduced-motion handling appears limited to CSS; change camera/world motion law as well');if(/\bdt\s*=\s*Math\.min\(/i.test(compact)&&/fpsFrames\s*\/\s*fpsAccum|\b1\s*\/\s*dt\b/i.test(compact))add('clamped-delta-performance-telemetry','warning','FPS appears derived from clamped simulation delta');
const sceneTextureSamples=(text.match(/texture\s*\(\s*uScene\b/g)||[]).length;if(sceneTextureSamples>=7&&!hasAdaptive)add('full-screen-post-without-adaptation','warning',`${sceneTextureSamples} scene-texture samples were detected in a full-screen post path without an adaptive-resolution contract`);
const errors=findings.filter(i=>i.severity==='error'),report={status:errors.length?'fail':'pass',file,flagship,metrics:{render_scale_candidates:likely,adaptive_ceiling:ceiling,reconstruction_detected:hasReconstruction,capture_lock_detected:hasCaptureLock,unicode_icon_buttons:unicodeButtons.length,world_size_m_candidate:Number.isFinite(worldSize)?worldSize:null,displayed_area_km2_candidate:Number.isFinite(displayedArea)?displayedArea:null,computed_bounding_area_km2:computed,adaptive_resolution_detected:hasAdaptive,source_files_scanned:sourceFiles.map(i=>path.relative(projectRoot,i.file).split(path.sep).join('/')||path.basename(i.file))},findings};
if(outPath){fs.mkdirSync(path.dirname(outPath),{recursive:true});fs.writeFileSync(outPath,JSON.stringify(report,null,2));}console.log(JSON.stringify(report,null,2));process.exit(report.status==='pass'?0:1);
