#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import http from 'node:http'; import {createRequire} from 'node:module';
const args=process.argv.slice(2),pos=args.find(a=>!a.startsWith('--'));if(!pos){console.error('Usage: input_audit.mjs <project-or-entry> [--out file] [--hold-ms 180] [--viewport 1280x720] [--executable path]');process.exit(2);}
const valueAfter=(f,d=null)=>{const i=args.indexOf(f);return i>=0?args[i+1]:d;},target=path.resolve(pos),isDir=fs.statSync(target).isDirectory(),root=isDir?target:path.dirname(target),entry=isDir?'index.html':path.basename(target),out=path.resolve(valueAfter('--out',path.join(root,'.forge','input-audit.json'))),hold=Math.max(60,Number(valueAfter('--hold-ms','180'))),vm=String(valueAfter('--viewport','1280x720')).match(/^(\d+)x(\d+)$/),viewport={width:Number(vm?.[1]||1280),height:Number(vm?.[2]||720)},executablePath=valueAfter('--executable',process.env.CHROME_PATH||null);
const types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.wasm':'application/wasm'};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent((req.url||'/').split('?')[0]);let f=path.resolve(root,pathname==='/'?entry:pathname.replace(/^\/+/,''));if(!f.startsWith(root+path.sep)&&f!==path.resolve(root,entry)){res.writeHead(403);res.end();return;}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);res.end();return;}res.writeHead(200,{'content-type':types[path.extname(f)]||'application/octet-stream','cache-control':'no-store'});fs.createReadStream(f).pipe(res);});
let playwright;try{playwright=await import('playwright')}catch{try{playwright=createRequire(path.join(root,'package.json'))('playwright')}catch{const r={status:'blocked',reason:'playwright not installed'};fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(r,null,2));console.log(JSON.stringify(r,null,2));process.exit(2);}}
const dot=(a,b)=>a.x*b.x+a.y*b.y+a.z*b.z,sub=(a,b)=>({x:a.x-b.x,y:a.y-b.y,z:a.z-b.z}),len=v=>Math.hypot(v.x,v.y,v.z),finiteVec=v=>v&&['x','y','z'].every(k=>Number.isFinite(Number(v[k])));
await new Promise((r,j)=>{server.once('error',j);server.listen(0,'127.0.0.1',r)});let browser,report={status:'pass',tests:{},limitations:[]};
try{browser=await playwright.chromium.launch({headless:true,...(executablePath?{executablePath}:{})});const page=await browser.newPage({viewport});await page.goto(`http://127.0.0.1:${server.address().port}/${encodeURI(entry)}`,{waitUntil:'networkidle',timeout:30000});
 const reset=async()=>page.evaluate(async()=>{const f=window.__FORGE__;if(typeof f?.prepareInputVerification==='function')return await f.prepareInputVerification();if(typeof f?.prepareVerification==='function')return await f.prepareVerification('input-audit');return null;});
 const probe=async()=>page.evaluate(()=>{const f=window.__FORGE__;if(typeof f?.getInputProbeState!=='function')return null;return f.getInputProbeState();});
 await reset();let p=await probe();if(!p||!finiteVec(p.position)||!finiteVec(p.forward)||!finiteVec(p.right)){report.status='blocked';report.reason='window.__FORGE__.getInputProbeState() must return finite position/forward/right';throw new Error('__BLOCKED__');}
 async function press(code){await reset();const before=await probe();await page.keyboard.down(code);await page.waitForTimeout(hold);await page.keyboard.up(code);await page.waitForTimeout(50);const after=await probe();const d=sub(after.position,before.position);return{before,after,delta:d,forwardDot:dot(d,before.forward),rightDot:dot(d,before.right),distance:len(d)};}
 const W=await press('KeyW'),S=await press('KeyS'),A=await press('KeyA'),D=await press('KeyD');report.tests.W={...W,pass:W.forwardDot>1e-4};report.tests.S={...S,pass:S.forwardDot<-1e-4};report.tests.A={...A,pass:A.rightDot<-1e-4};report.tests.D={...D,pass:D.rightDot>1e-4};
 await reset();const db=await probe();await page.keyboard.down('KeyW');await page.keyboard.down('KeyD');await page.waitForTimeout(hold);await page.keyboard.up('KeyW');await page.keyboard.up('KeyD');await page.waitForTimeout(50);const da=await probe(),dd=sub(da.position,db.position),diag=len(dd),single=Math.max(W.distance,D.distance,1e-9),ratio=diag/single;report.tests.diagonal={distance:diag,singleReference:single,ratio,pass:ratio<=1.25&&ratio>=.65};
 const grounded=[W.after,S.after,A.after,D.after,da].filter(x=>typeof x.grounded==='boolean');if(grounded.length)report.tests.grounding={pass:grounded.every(x=>x.grounded===true),samples:grounded.map(x=>x.grounded)};else report.tests.grounding={pass:null,status:'not-applicable'};
 const failures=Object.values(report.tests).filter(t=>t.pass===false);if(failures.length)report.status='fail';
}catch(e){if(String(e?.message)!=='__BLOCKED__'){report.status='fail';report.fatal=String(e?.stack||e);}}finally{await browser?.close();server.close();}
fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));process.exit(report.status==='pass'?0:report.status==='blocked'?2:1);
